### ISSUE TITLE
Feature request - print command

### ISSUE THREAD

**Issue by AntonKrug** [renode/renode#10]
Add the equivalent of a "print/printf" command. At the moment something similar can be achived with:

`log "text I want to output" 3`

setting the priority to 3 will make it into a error and will be output even when logLevel will not be verbose, but using a logger means that a error logger text is premented, which might be undesired in some situations

`12:40:00.5256 [ERROR] Script: text I want to output`

**Comment by PiotrZierhoffer** [comment]
For now we have `console_log` command, that does exactly that: prints some text to console.

It is not supposed to be used in a generic environment, as it disregards all `logFile` and `logLevel` settings.
