### ISSUE TITLE
Add support for auto-detection of target architecture in GDB

### ISSUE THREAD

**Issue by AntonKrug** [renode/renode#11]
When attaching to Renode with gdb from eclipse it assumes 64bit riscv which should then detect the 32bit riscv cpu. For Renode sessions require this to be set `set arch riscv:rv32`. In past this was necessary with real hardware as well, but was later fixed by SiFive guys.

These links should be relevant to this problem:

https://github.com/riscv/riscv-binutils-gdb/issues/54
https://github.com/riscv/riscv-openocd/issues/101
https://github.com/riscv/riscv-binutils-gdb/commit/6b51d01bf018ec41a5dfb36c276b68822a0ac6eb

**Comment by PiotrZierhoffer** [comment]
Renaming the title as this is in fact a more general feature we lack

**Comment by PiotrZierhoffer** [comment]
This is done via 3737353

**Comment by xobs** [comment]
Looking through old issues, I wanted to add a comment about this for posterity's sake.

This is a common problem with Eclipse.  It ships with the riscv64 toolchain running in "multiarch" mode, so it defaults to 64-bits even though it is also used to build 32-bit binaries.  If you run GDB directly it'll read the configuration out of the ELF header and select the appropriate target, but Eclipse wraps it so GDB falls back to its default.  Which as you've seen is 64-bits

The solution is to go to `GDB Client Setup` and add `set arch riscv:rv32`.
