### ISSUE TITLE
Renode does not work with STM32F746 Discovery with STM32Cube example

### ISSUE THREAD

**Issue by xiongyu0523** [renode/renode#111]
I have noticed there is a RCC bug has been fixed recently but it still can't solve my problem and even worse.

I have a very simple application based on stm32cube sample code that prints some characters from USART1. And I can't see anything on sysbus.usart1 virtual analyzer. 

More interesting findings:
With previous stm32f7 platform description file (RCC is only 4 bytes), when I disable the standard STM32cube clock init api SystemClock_Config(), I can see my logs get printed.
With using new the latest description files (RCC is fixed to 0x400 bytes), I still can't get it works even I had disabled the above clock init API in source code

New to Renode. I can only report my observations. Could you try to run any STM32Cube based examples?

**Comment by mateusz-holenko** [comment]
With the extended platform definition from b240afa03e24407d00631576de2cd762e2a2806c you should be able to run STM32Cube-based examples in Renode.

We also added a test to verify this in e946a20965ffc46ad180a718953c46ccc2680c9f.
