### ISSUE TITLE
STM32L1 svd file downloaded contains F7 svd

### ISSUE THREAD

**Issue by karlp** [renode/renode#126]
The file https://dl.antmicro.com/projects/renode/svd/STM32L1xx.svd.gz doesn't contain the L1 svd, it contains an F7x6 svd.

**Comment by mgielda** [comment]
Thanks @karlp, indeed. We'll need to see why and fix this.

**Comment by mateusz-holenko** [comment]
I confirm that there was a bug and both https://dl.antmicro.com/projects/renode/svd/STM32L1xx.svd.gz and https://dl.antmicro.com/projects/renode/svd/STM32F7x6.svd.gz pointed to the same file.

It is fixed now and L1 svd is correct.
