### ISSUE TITLE
a sample resc file for running zephyr http server over frdmk64f

### ISSUE THREAD

**Issue by hakehuang** [renode/renode#132]
is it possible to have a sample resc file to demo how to run zephyr http server over frdmk64f?

**Comment by PiotrZierhoffer** [comment]
Hi Hake

As we currently don't have any K64F samples, we'll verify if everything works fine with the HTTP setup.

**Comment by hakehuang** [comment]
@piotr-binkowski  thanks a lot, I check the test code, and try them, they works fine, just do not know how to connect to a wired network. this would be great if we can have a demo which create two instances and do tcp/udp transactions.

**Comment by jensschroer** [comment]
@hakehuang Do you want two instances running in Renode or one in Renode and one outside of Renode?

**Comment by hakehuang** [comment]
@jensschroer one in Renode and one outside of Renode?

**Comment by jensschroer** [comment]
@hakehuang you would probably want to wait until #147 is merged, as it adds support for the PHY and allows your code to bring up the Ethernet interface automatically.

Having said that, is your host OS Linux? If so, I can provide the steps you need to create a connection between your simulation and the host machine.

**Comment by PiotrZierhoffer** [comment]
Hake, Jens, #147 is now merged

**Comment by jensschroer** [comment]
> Hake, Jens, #147 is now merged

Thank you!
