### ISSUE TITLE
Build for ARM64

### ISSUE THREAD

**Issue by kevingoh** [renode/renode#134]
Hi,

I am looking for the possibility to run renode on my Rasberry Pi 4B.
Please enlighten me how (if it is possible) to build renode for arm64.

**Comment by PiotrZierhoffer** [comment]
Hi @kevingoh 

This is, currently, not possible. Renode supports only AMD64 host machines.

It is a long term goal to support ARM hosts (especially on Linux) but we're not there yet.

If this answers your question, I'll close the issue

**Comment by kevingoh** [comment]
Hi @PiotrZierhoffer 

Yes it does! Hopefully we will get there one day then Renode will really serve the purpose of a budgetary solution for HW simulation.

Thanks
