### ISSUE TITLE
put output from showAnalyzer sysbus.uart in file?

### ISSUE THREAD

**Issue by mtrzas** [renode/renode#137]
Hi,

I want to use Catch2 in Renode for automated unit tests for our firmware.
To put the test results in the sysbus.uart window works. But I want to put the windows output in a file.

I tried renodes log funktion:
(machine-0)sysbus LogPreipheralAccess sysbus.uart
But for automated unit tests is this file not very usable.

Thanks for help!

**Comment by PiotrZierhoffer** [comment]
Hi @mtrzas

You can use `uart CreateFileBackend @/path/to/file`.

Does this help?

**Comment by PiotrZierhoffer** [comment]
Also, for testing I recommend inspecting `.robot` files - they are great for this kind of scenarios
