### ISSUE TITLE
Default font for monitor is tiny on high DPI displays

### ISSUE THREAD

**Issue by whoopsmith** [renode/renode#145]
I see references to default font size for termsharp in ConfigurationManager but its not clear to me how that gets set.

Is there a way to change the font size?

**Comment by whoopsmith** [comment]
Update:  I found Ctrl-Shift-+ (on Linux) that increases the font size but not where to set the default.

**Comment by PiotrZierhoffer** [comment]
Hi @whoopsmith 

You can set the default font face and size in `~/.config/renode/config`. Look for `font-size` in the `[termsharp]` section.

**Comment by whoopsmith** [comment]
@PiotrZierhoffer Thank you. That works bur does not seem to also scale the default terminal size. I don't see a config option for the terminal size.  Is that a configure option?

**Comment by PiotrZierhoffer** [comment]
@whoopsmith no, we do not have scaling ability at the moment. 

I can see that adding this as a config option should be relatively trivial, so we'll try to do it soon.

**Comment by PiotrZierhoffer** [comment]
These options are now on master. To use them, please compile the latest Renode and run it at least once - the options will be added to your config file as 
```
window-width = 700 
window-height = 400
```

**Comment by whoopsmith** [comment]
Thank you.  I've updated to latest master and I can confirm the above works for me.
