### ISSUE TITLE
STATUS register of EFR32_USART not updated in asynchronous mode

### ISSUE THREAD

**Issue by basilfx** [renode/renode#155]
The EFR32_USART implementation does not update the [`transferCompletedFlag`](https://github.com/renode/renode-infrastructure/blob/master/src/Emulator/Peripherals/Peripherals/UART/EFR32_USART.cs#L218-L220) flag when the device operates in asynchronous mode (the default). In that case, code like [`while (!(usart->STATUS & USART_STATUS_TXC)) {}`](https://github.com/RIOT-OS/RIOT/blob/master/cpu/efm32/periph/uart.c#L194) blocks forever.

I attached a `hello-world` application from RIOT-OS. that should print the text below, but stops printing after the first line.

```
main(): This is RIOT! (Version: 2021.01-devel-952-g36d20-feature/renode)
Hello World!
You are running RIOT on a(n) sltb001a board.
This board features a(n) efm32 MCU.
```

[hello-world.elf.zip](https://github.com/renode/renode/files/5556264/hello-world.elf.zip) for the [SLTB001a](https://github.com/basilfx/RIOT/tree/feature/renode/boards/sltb001a/dist/renode).

**Comment by mateusz-holenko** [comment]
Thanks for your contribution @basilfx!
