### ISSUE TITLE
Add support for STIR register for cortex m series

### ISSUE THREAD

**Issue by rgujju** [renode/renode#183]
While building a zephyr application for NRF52840DK board, the `trigger_irq` API fails since it uses the NVIC STIR register to trigger the interrupt. 
Adding support for this register would allow us to build for cortex-m devices without modifying the API. 
A test for this is present in zephyr `tests/kernel/interrupt`, build using `cmake .. -DBOARD=nrf52840dk_nrf52840`

**Comment by ajelinski** [comment]
The issue has been fixed by https://github.com/renode/renode/commit/df5fca66d1236238376f47cddfa05bb1e8ae2008 .
