### ISSUE TITLE
Cosmetic minor issue with UART on Windows and the first line 

### ISSUE THREAD

**Issue by AntonKrug** [renode/renode#19]
This can be experienced with all Mi-V examples, but the blinkies examples have a new line as the first line so it's not visible. But when the text is modified (so there is a text on the first line):

```c
const char * g_hello_msg =
"System timer Blinky Example         \n\r\n\r\
Observe the LEDs blinking on the board. The LED pattern changes \
every time a system timer interrupt occurs\r\n";
```

Then even blinkies expierence this problem, it can be observed on the mandelbrot/raytracer as well. Looks like the issue is linked with some event as mouse events (left mouse button clicking or scrolling the wheel) will make it appear for about 0.5second before disappearing away again.

**Comment by PiotrZierhoffer** [comment]
Fixed in v1.5
