### ISSUE TITLE
can't download the elf file

### ISSUE THREAD

**Issue by zzzh** [renode/renode#21]
[ERROR] Failed to download from http://antmicro.com/projects/renode/riscv-liteos-port.elf-s_689820-e68d3bcf0a12c25daa66fc51e474281bcbed2fc7, reason: Timeout.

it happened when I try the command "include @scripts/single-node/miv.repl" following https://renode.readthedocs.io/en/latest/tutorials/miv-example.html

any ideas?

**Comment by zzzh** [comment]
Actually, it's not a renode issue, but seems the site holding the elf files can't be reached.
Please provide a way to download the elf files so that people who are interested  can see how renode works.

**Comment by PiotrZierhoffer** [comment]
It could have been a temporary issue. Could you please verify once again?

Once the binary is downloaded, it is cached - so you have to download them only once on each machine.

If you have your own software for this platform, you can also use it by setting the $bin variable (`$bin=@path/to/file.elf`).

**Comment by AntonKrug** [comment]
Probably it was temporary as I can download it without any issue.

**Comment by zzzh** [comment]
Hi, PiotrZierhoffer and AntonKrug, 

I think it's because some internet issues that make it impossible to access that site from where I am, and it may also happen to others.

So, would you please to put the elf files at github too?

**Comment by AntonKrug** [comment]
Would this help?

[riscv-liteos-port.zip](https://github.com/renode/renode/files/2210573/riscv-liteos-port.zip)

(unzip it after download)

**Comment by AntonKrug** [comment]
That's up to the Antmicro guys how they would prefer to structure it. I just wanted to give you something to get you going in the meantime.

**Comment by AmeyaVS** [comment]
Hello,

I have similar issue while running the `test.sh` to run the sanity tests.

Here is a short list:
- Should Generate Interrupts On Gpio High Level:  
    ```text
    TargetInvocationException: Exception has been thrown by the target of an invocation. KeywordException: Could not execute command 'sysbus LoadELF @http://antmicro.com/projects/renode/riscv-interrupt-blinky-gpio_interrupts-level_high.elf-s_134928-e5184e20f1458b9784c10c48ad8fde0a738cfb65': Failed to download http://antmicro.com/projects/renode/riscv-interrupt-blinky-gpio_interrupts-level_high.elf-s_134928-e5184e20f1458b9784c10c48ad8fde0a738cfb65, see log for details. 
    ```

- Should Generate Interrupts On Gpio Low Level:  
    ```text
    TargetInvocationException: Exception has been thrown by the target of an invocation. KeywordException: Could not execute command 'sysbus LoadELF @http://antmicro.com/projects/renode/riscv-interrupt-blinky-gpio_interrupts-level_low.elf-s_134928-3d7a09bb3cf434fde9bf9d2c29888ffb11861c0b': Failed to download http://antmicro.com/projects/renode/riscv-interrupt-blinky-gpio_interrupts-level_low.elf-s_134928-3d7a09bb3cf434fde9bf9d2c29888ffb11861c0b, see log for details. 
    ```

I have setup the same development environment on two different systems(Ubuntu 16.04 LTS).
And in only one of the system I am observing the same failure repeatedly, also I am able to download the binaries on the system browser and command-line.

Maybe the issue is related.

-Ameya

**Comment by zzzh** [comment]
@AmeyaVS    I would say the system you observed same failure may have internet issue, just like what happened on my system.

**Comment by AmeyaVS** [comment]
@zzzh I tried today, somehow it is now working.
The thing is I was able to download the files using the browser or command-line yesterday, when I faced this issue.

**Comment by zzzh** [comment]
@AmeyaVS good to know it's working now, the reason of your issue should be in the log.
