### ISSUE TITLE
Unable to create custom CPU

### ISSUE THREAD

**Issue by xobs** [renode/renode#219]
It should be possible to create a custom CPU, however doing so does not currently seem possible. Something is missing within the Renode C# compiler.

As an example CPU:
```cs
using System;
using ELFSharp.ELF;
using Antmicro.Renode.Utilities;
using Antmicro.Renode.Logging;
using Antmicro.Renode.Peripherals.Timers;

namespace Antmicro.Renode.Peripherals.CPU
{
    public class AesVexRiscv : VexRiscv
    {
        public AesVexRiscv(Core.Machine machine,
            uint hartId = 0,
            IRiscVTimeProvider timeProvider = null,
            PrivilegeArchitecture privilegeArchitecture = PrivilegeArchitecture.Priv1_10,
            string cpuType = "rv32im",
            bool builtInIrqController = true) : base(machine, hartId, timeProvider, privilegeArchitecture, cpuType, builtInIrqController)
        {
            // RegisterCustomInstructions();
        }
    }
}
```

If this is placed into a file called `vexriscv-aes.cs` and included with `i @vexriscv-aes.cs`, Renode produces the following output:

```
(vexriscv-aes-test) i @vexriscv-aes.cs
15:47:18.1881 [INFO] Including script: D:\Code\Betrusted\aes\vexriscv-aes.cs
Errors during compilation or loading:
There were compilation errors:
D:\Code\Betrusted\aes\vexriscv-aes.cs(70,32): error CS0246: The type or namespace name `VexRiscv' could not be found. Are you missing an assembly reference?
D:\Code\Betrusted\aes\vexriscv-aes.cs(75,13): error CS0246: The type or namespace name `PrivilegeArchitecture' could not be found. Are you missing an assembly reference?
(vexriscv-aes-test)
```

It seems as though the name `VexRiscv` and `PrivilegeArchitecture` are not available. Similarly, `RiscV32` is unavailable, so even a no-op CPU cannot be created.

**Comment by PiotrZierhoffer** [comment]
The interesting thing is that the following works:

    (monitor) i @scripts/single-node/litex_vexriscv_zephyr.resc 
    (machine-0) Clear
    (monitor) i @vexriscv-aes.cs 

This means that we have access to peripherals that are already loaded. We can load them if needed, but we don't know which ones will we need in this case. This should be doable somehow.

**Comment by PiotrZierhoffer** [comment]
Instead of loading and clearing you can use the following command before you include the `cs` file:

    EnsureTypeIsLoaded "Antmicro.Renode.Peripherals.CPU.VexRiscv"

It's a bit fragile, so watch for typos.

**Comment by PiotrZierhoffer** [comment]
I'll close this issue but feel free to reopen or file a new one if you have additional questions
