### ISSUE TITLE
Failed Building the Renode.sln on Visuan Studio

### ISSUE THREAD

**Issue by Emna-b** [renode/renode#234]
I was setting up the Renode build environment, and when I tried to build the Renode.sln file using Visual Studio I got multiple errors. (This step is mentioned in the Renode Documentation)
Errors : 
-error with the code : CS0246  
-components not found
Any help would be appreciated! 

![yh](https://user-images.githubusercontent.com/69528425/127752063-f950b83e-d5f9-40fc-ab06-8f1b20930e8b.PNG)

**Comment by PiotrZierhoffer** [comment]
When building Renode for the first time on each clone you need to run `./build.sh`. This should

a) download all submodules
b) download additional build dependencies.

If this fails for you, please provide the full output of build.sh

**Comment by Emna-b** [comment]
When I ran ./build.sh on Cygwin this are the errors I got : 
./build.sh: line 58: xbuild: command not found

![thisbuild shErrorFinal](https://user-images.githubusercontent.com/69528425/128090384-174558a0-9858-4495-80ee-0c56161c7374.PNG)

**Comment by PiotrZierhoffer** [comment]
I'm not sure why do you run the first command `cd ./lib/Migrant/tools`? This is just a helper script, it won't work and you don't need it.

Just run `./build.sh` from the top Renode dir.

**Comment by PiotrZierhoffer** [comment]
Let's close this for now, please reopen if you have any other comments or questions
