### ISSUE TITLE
How to load more than one elf or binary file using renode?

### ISSUE THREAD

**Issue by jycc1991** [renode/renode#240]

**Comment by PiotrZierhoffer** [comment]
It's actually quite simple - you just repeat the command.

For binaries you have to provide load addresses, for ELFs that's not required.

Please note that Renode will automatically set starting PC based on the **last** ELF you loaded, so keep this in mind.

So

```
sysbus LoadELF @pathToElf
sysbus LoadBinary @pathToBinary 0x1000
sysbus LoadELF @pathToElfThatWillSetThePC
```

You can see an example in the [ARVSOM script](https://github.com/renode/renode/blob/master/scripts/single-node/arvsom.resc)

**Comment by PiotrZierhoffer** [comment]
I'll close this issue but feel free to reopen or file a new one if you have additional questions
