### ISSUE TITLE
USB support for STM32

### ISSUE THREAD

**Issue by kaizoku-oh** [renode/renode#241]
Is there a ready to use USB peripheral model for STM32 MCUs that can be simply added to the .repl file and used?

**Comment by mateusz-holenko** [comment]
Hi @kaizoku-oh , thanks for the question.

Currently we do not support any USB controllers for STM32-based platforms.

**Comment by kaizoku-oh** [comment]
Thanks for the answer

**Comment by shareefj** [comment]
@mateusz-holenko What's the status here a year later?  Is there any plan to add USB support?

**Comment by cagnulein** [comment]
hi @mateusz-holenko any plan about this?
