### ISSUE TITLE
Support for STM32F767 and STM32H755

### ISSUE THREAD

**Issue by anirudh-upadhya** [renode/renode#248]
Could you please add support and necessary `.repl` and `.resc` for STM32F767 and STM32H755?
Also can you please share a document/template to create our own `.repl` and `.resc` scripts ?

**Comment by PiotrZierhoffer** [comment]
@anirudh-upadhya you will notice that with 9f7d402 we added a platform file for STM32H743, which is fairly similar to STM32H755

**Comment by anirudh-upadhya** [comment]
Hi @PiotrZierhoffer 
Thank you very much for the update.
