### ISSUE TITLE
[STM32] Write Uart -> receive uart reply --> write log reply

### ISSUE THREAD

**Issue by RAnastacioo** [renode/renode#256]
Hi, 
I created an elf stm32 which gives a serial response whenever I send a uart message. Now the problem is the uart (read/write) renode...
Is it possible to cycle? ( Write Uart mensage --> receive uart reply --> write reply log file )
Are there any examples to help write\read uart (hinode)? And to write a uart response log?

greetings

**Comment by PiotrZierhoffer** [comment]
Hi @RAnastacioo 

I'm not exactly sure what you are trying to achieve. Can you please write some more details about what exactly are you trying to do?

**Comment by RAnastacioo** [comment]
Thank you for your help
Basically I want to establish a uart communication, where the MCU and Computer and send messages to each other.
The MCU programming part is relatively easy. Communication across the renode I don't know how to do it.

**Comment by PiotrZierhoffer** [comment]
There are three things you can do:

- save UART output to a file - run `uart CreateFileBackend @path/to/your/file` in the Monitor after you load the platform (but before you start it)
- connecting UART to /dev/pty - described here https://renode.readthedocs.io/en/latest/host-integration/uart.html#uart-pty-terminal
- connecting UART to a socket - https://renode.readthedocs.io/en/latest/host-integration/uart.html#socket-terminal

The two latter option are good if you need interactivity, the first one is there to just dump the data.

As a bonus, we also have an ability to record [asciinema captures](https://asciinema.org/): `uart RecordToAsciinema @path/to/your/recording`.

Hope this helps!

**Comment by PiotrZierhoffer** [comment]
I'll close the issue, but feel free to reopen or file a new one if you have additional questions
