### ISSUE TITLE
ELF generated with greenhills compiler does not load

### ISSUE THREAD

**Issue by Ahelion** [renode/renode#257]
Hello,
The project is stm32, compiler: greenhills v2017.1.4.
When loading into renode the binary, everything is ok.
When I want to load the elf(LoadELF and LoadSymbolsFrom ), i get this.

```
Renode, version 1.12.0.25160 (44d6786a-202104021357)
(monitor) i $CWD/renode_config_debug.resc There was an error executing command 'sysbus LoadSymbolsFrom $elf'
Error while loading ELF: End of stream reached with 132115904 byte left to read..
 End of stream reached with 132115904 byte left to read.
There was an error executing command 'runMacro $reset'
' failed.ine '    sysbus LoadSymbolsFrom $elf
```

The reported size is not even the correct one:

"11711728" the elf file size in bytes
"132115904" the size reported by renode..

The elf is read properly by tools like readelf and gdb.
Does anybody now what the issue can be?

**Comment by Ahelion** [comment]
I had some time to check.
The ElfSharp library reads past the elf file. For some reason it sees the elf bigger then it is. it is trying to read past the end of the elf.
Somebody in the calling code I think is telling it the file is bigger.

**Comment by Ahelion** [comment]
[Z03In005_App_default.zip](https://github.com/renode/renode/files/7461466/Z03In005_App_default.zip)
@PiotrZierhoffer  Hopefully you can see it attached to this comment.

**Comment by PiotrZierhoffer** [comment]
Yes, I can see it and can confirm the issue. We'll try to find the root cause.

**Comment by Ahelion** [comment]
Hello, any news?
Even if there is an updated .dll that I can use for my work, it would be great.

**Comment by mateusz-holenko** [comment]
https://github.com/renode/renode/commit/53b543f75716ff83f7f916cd2f7c84e4a994aefa fixes problems with loading misaligned NOTE sections from the ELF file.

This allowed us to load the provided binary without errors. Could you check if it works for your other binaries, @Ahelion?

**Comment by mateusz-holenko** [comment]
We consider this as done, if you have any additional questions feel free to open a new issue.
