### ISSUE TITLE
support STM32H747I-DISCO board

### ISSUE THREAD

**Issue by jjpark78** [renode/renode#264]
do renode has roadmap for support stm32 H series mcu or H747-Disco board ?

it will be really great for me.

if you can support it through commercial plan, let me know

thanks.

**Comment by PiotrZierhoffer** [comment]
Hi @jjpark78 

Currently we have no plans for the H series, but of course we do provide commercial support and we'd be happy to discuss this further. 

Please reach out via contact@antmicro.com

**Comment by PiotrZierhoffer** [comment]
@jjpark78 with 9f7d402 we added a very basic platform file for STM32H743, which should be similar to what you're looking for.

We still invite you to reach out via email if you require more robust support of the platform.
