### ISSUE TITLE
Test with renode and code coverage report

### ISSUE THREAD

**Issue by jjpark78** [renode/renode#266]
i just curious about when testing with renode using Robot Framework, renode can measure code coverage or not

when develop web apps, e2e test can generate some of coverage report and mocking environment is not that hard

but in my opinion, unit test in embedded is too expensive, cause of need to mocking everything

so, i thinks renode can do this, it will be really great !!!

**Comment by PiotrZierhoffer** [comment]
Hi @jjpark78 

Tracking execution is something that can be easily done with Renode, but with the abundance of coverage tools out there it's difficult to select just one.

You can call `cpu SetHookAtBlockBegin` and `cpu SetHookAtBlockEnd` in your script, providing it with a Python script that will log specific information. In these scripts you have access to the following variables:

- `pc` - current program counter
- `size` - number of instructions
- `cpu` - giving you access to most of the CPU methods

For example

```
cpu SetHookAtBlockBegin "print(str(pc) +' ' +str(size))"
```

If you are interested in any particular coverage reporting tool, please drop us an email.

**Comment by mateusz-holenko** [comment]
FYI @jjpark78: In https://github.com/renode/renode/commit/2a79488d8126dfa9edd91a0666720ddb8938fe0f we added the execution tracer module that can dump executed PCs / opcodes to a separate file.

**Comment by jjpark78** [comment]
> FYI @jjpark78: In [2a79488](https://github.com/renode/renode/commit/2a79488d8126dfa9edd91a0666720ddb8938fe0f) we added the execution tracer module that can dump executed PCs / opcodes to a separate file.

that a good update. 

how can i use this from robot test framework ?

**Comment by mateusz-holenko** [comment]
At the moment the module supports dumping a trace to a file, so you need to search the file content as in: https://github.com/renode/renode/blob/master/tests/unit-tests/execution-tracing.robot#L27.

**Comment by PiotrZierhoffer** [comment]
Closing the issue for now, feel free to reopen if you need further input.

**Comment by mkschreder** [comment]
@PiotrZierhoffer how can we get an lcov coverage report from the trace?
