### ISSUE TITLE
Emulate UART port or  UART Device to read serial data 

### ISSUE THREAD

**Issue by Nileshhampiholi** [renode/renode#275]
Hello ,
I am trying to emulate a device (or just emulating a port works for me) to write some data to serial port of host device.

I have a software that reads serial data specifically from - /dev/serial/by-id/ file_name.

I have tried following approaches.

    Tried emulating a stm3f4_discovery
    emulating arduino nano 33 ble

    Tried emulating a stm3f4_discovery

    I have stm32cube ide with code ready to be flashed into the board so that the board or device write 0 and 1 to the serial port
    (monitor) emulation CreateUartPtyTerminal "term" "/tmp/uart"
    mach create
    machine LoadPlatformDescription @platforms/boards/stm32f4_discovery.rep
    connector Connect sysbus.uart1 term

And it works until here.

Further I don't understand what the documentation says -- what does this mean?
(Finally, open the terminal application on your host machine (screen/picocom/PuTTY/etc.) and attach it to the /tmp/uart file. You can interact with it just like with the hardware.)

Attach how?

    emulating Arduino nano 33 ble

    I have Arduino code that write 0 and 1 to the serial port using serial1 as mentioned in the documentation.
    In renode I run the script s @scripts/complex/arduino_nano/nrf52840_arduinoIDE_integration.resc
    I flash the code in Arduino ide and see out put in uart analyser

But if I use python and try to read data from serial device connected to the port I don't see anything coming out. .

**Comment by mateusz-holenko** [comment]
This topic is further discussed in https://github.com/renode/renode-docs/issues/29.
