### ISSUE TITLE
RV64G: Possibly fcvt.lu.d not working correctly

### ISSUE THREAD

**Issue by AntonKrug** [renode/renode#28]
Made small replicator, enable double floating point abi and add the math library -lm

C code:
```
#include <stdint.h>
#include <float.h>

void test(void) {
	double   input   = 1.23456;
	uint64_t result1 = input;
	int64_t  result2 = input;

	while(1) {
	}
}
```

Assembly:
```
 6                void test(void) {
                  test:
0000000008003460:   addi    sp,sp,-48
0000000008003464:   sd      s0,40(sp)
0000000008003468:   addi    s0,sp,48
 7                	double input = 1.23456;
000000000800346c:   auipc   a5,0x1
0000000008003470:   addi    a5,a5,-228 # 0x8004388
0000000008003474:   fld     fa5,0(a5)
0000000008003478:   fsd     fa5,-24(s0)
 8                	uint64_t result1 = input;
000000000800347c:   fld     fa5,-24(s0)
0000000008003480:   fcvt.lu.d       a5,fa5,rtz
0000000008003484:   sd      a5,-32(s0)
 9                	 int64_t result2 = input;
0000000008003488:   fld     fa5,-24(s0)
000000000800348c:   fcvt.l.d        a5,fa5,rtz
0000000008003490:   sd      a5,-40(s0)
```

For some reason `fcvt.lu.d` step no matter what it will set the result to 0x8000000000000000. I tried few of other fcvt variants (32-bit to 32-bit and 64-bit to 64-bit) and they seem to work, while the 32-bit to 64-bit and 64-bit to 32-bit misbehave (for example fcvt.lu.d). This might not be the only affected instruction (casting back in the reverse order is affected as well) while casting within the same size (32-bit or 64-bit) between int and float registers works.

**Comment by PiotrZierhoffer** [comment]
Fixed on master with
