### ISSUE TITLE
Missing STM32F4 PWR peripheral

### ISSUE THREAD

**Issue by PhilippFinke1988** [renode/renode#284]
I currently ran into an issue where my firmware got stuck due to waiting for the ODRDY bit in the power control status register of the STM32F4 PWR peripheral to become one. In order to fix this I implemented a model of the STM32 PWR peripheral. I will create a pull request with this fix as this may be handy for others too.

**Comment by PiotrZierhoffer** [comment]
Closing, as the model is merged. Thanks for your contribution!
