### ISSUE TITLE
AArch64 emulation support

### ISSUE THREAD

**Issue by Gerharddc** [renode/renode#293]
From what I can tell, Renode does not yet support emulating AArach64 systems yet, only "classic" ARM. Is this correct and if so, are there any plans to support this in the future?

Along those same lines I am also curious about support for multiple cores.

**Comment by PiotrZierhoffer** [comment]
Hi @Gerharddc , that's correct - AArch64 is not currently supported. It's definitely on the list, but I cannot give you any precise dates.

Multicore support is currently enabled in RISC-V. It will probably be added ARM cores along with aarch64.

**Comment by ImmortalBuka** [comment]
@PiotrZierhoffer is multicore support enabled only for riscv64?

**Comment by PiotrZierhoffer** [comment]
@ImmortalBuka at the moment this is correct, in the sense that we support RISC-V atomic instructions across cores. However, it's also possible to have separate cores with external synchronization mechanisms, modeled as bus peripherals. 

Sadly, at the moment we do not have public demos with this functionality.

**Comment by bitbytedog** [comment]
Any update on aarch64 support? It would be very useful for my current work with the ZyncMP SoC.

**Comment by PiotrZierhoffer** [comment]
Related to #431, we'll continue there as we're getting close to having an initial support released
