### ISSUE TITLE
Upgrade to RobotFramework 4 causes Error

### ISSUE THREAD

**Issue by Xcross74** [renode/renode#311]
Hi All,

I have been running Renode tests on RobotFramework v3.1 but when upgrading to v4.1.3 I get an error immediately and don't know why.
![image](https://user-images.githubusercontent.com/102161587/159709355-e19f5492-2d30-496f-aaa3-3992e698f6fd.png)
If I revert back to v3 I can run my tests again. I'm new to this framework so maybe someone can point me in the right direction ?

Below is a pip freeze of installed packages, perhaps one of them is incompatible ? Thanks !
[python_installation.txt](https://github.com/renode/renode/files/8333353/python_installation.txt)

**Comment by PiotrZierhoffer** [comment]
Hi @Xcross74 

We have changed the supported Robot version some time ago, from 3.X to 4.0.1. The API changed significantly and we have no backwards compatibility

It happened last year - which version of Renode are you using? I would assume it's either the official release or some older commit?

Please take a look at https://github.com/renode/renode/blob/master/tests/requirements.txt for current pip requirements.

**Comment by Xcross74** [comment]
thank you for the reply.
I've double checked the requirements and just in case did a pip install -r requirements.txt with the ones from your link, however still no difference.
Attached is the Renode version I am using. It is the v1.12. Is this one not compatible with Robot v4 do you think ?
![image](https://user-images.githubusercontent.com/102161587/159797911-fa05de49-ec74-423e-bc03-e82d393a0506.png)

**Comment by PiotrZierhoffer** [comment]
This is our official release, which relies on Robot 3.1.

I'd recommend using one of your latest builds from https://builds.renode.io/

The Renode 1.13 is going to happen quite soon, and it will rely on Robot 4.0.1

**Comment by Xcross74** [comment]
thanks
