### ISSUE TITLE
platforms: cpus: stm32f412: incorrect RCC address

### ISSUE THREAD

**Issue by aunsbjerg** [renode/renode#328]
As per table 1 in the STM32F412 reference manual (see picture), the RCC address should be 0x40023800. For my Zephyr application on a custom board, this results in the debug UART not outputting anything and probably more stuff.

![image](https://user-images.githubusercontent.com/1454086/166876213-864e3c04-9886-4b53-bd32-d4021f7132d9.png)

Issue is found on `v1.13.0`.

I'll add a PR fixing this issue.

**Comment by mateusz-holenko** [comment]
Thanks @aunsbjerg for spotting this typo. Your PR has been accepted and merged upstream.
