### ISSUE TITLE
peripherals: stm32_adc: possible incorrect end-of-conversion interrupt logic

### ISSUE THREAD

**Issue by aunsbjerg** [renode/renode#332]
Was struggling getting my Zephyr application working against the ADC emulator in Renode and I believe I have identified a logic error in the handling of the end-of-conversion logic.

Reading the STM32F412 datasheet is a bit confusing, as the descriptions for the end-of-conversion bit (EOC) in the status register and the end-of-conversion selection bit (EOCS) in the control register are a bit contradictory. From section 13.12.1 (ADC status register):

![image](https://user-images.githubusercontent.com/1454086/167693612-81f2349e-a191-42bd-a794-580fc7e986be.png)

And from section 13.12.3 (ADC control register 2):

![image](https://user-images.githubusercontent.com/1454086/167693809-4b6ece49-babb-4640-856b-57991aa26b47.png)

The STM32_ADC emulator needs EOCS=1 to fire the EOC interrupt, but that bit is not set by Zephyr. Adding it to zephyr makes everything work.

I think the correct solution is to make the renode simulator handle non-sequence, interrupt enabled conversions correctly. I'll add a PR with a solution that seems to work for me. 

It might be that I'm wrong, and that the Zephyr STM32 ADC shim is not implemented correctly.

**Comment by mateusz-holenko** [comment]
Thanks for reporting the issue and creating a PR, @aunsbjerg. This is now fixed upstream.
