### ISSUE TITLE
Add extra columns for hps status method in renode

### ISSUE THREAD

**Issue by EuniceMadya** [renode/renode#338]
**Platform Used:** Debian GNU/Linux

**Renode Version:** 1.13.0.2537

**Platform to run on:** Debian GNU/Linux

Right now, inside [HPSHostController](https://github.com/renode/renode-infrastructure/blob/e6c619cd001c7629d4987021c60e315705ee6e41/src/Emulator/Extensions/Mocks/HPSHostController.cs#L142) only 12 registers' values are read and rendered, while when running `hps status`, we have 19 registers with different values, and therefore we could add few columns for the remaining registers.

**Comment by PiotrZierhoffer** [comment]
Sure, we'll look into this!

**Comment by EuniceMadya** [comment]
I'm working on it right now, and communicating with the HPS team regarding this too, but any help would be appreciated!

**Comment by PiotrZierhoffer** [comment]
@EuniceMadya for the record, are these changes what you were looking for in the context of this issue?

**Comment by EuniceMadya** [comment]
Yup looks good!

**Comment by mateusz-holenko** [comment]
Great, we'll merge it upstream soon.

**Comment by mateusz-holenko** [comment]
Update to the `HPSHostController` is now merged upstream: d6e1ff54acf29d3f22460d181564c43a018569b1.
