### ISSUE TITLE
Incorrect handling of the GPIOx_BRR register for STM32

### ISSUE THREAD

**Issue by dkDeman** [renode/renode#343]
During executing one of the simple test cases, when need to perform simple operations one after another: LED on, LED on. 

Test case:
// Set UserLED Port to high level 
UART > led on 
// Check that LED is turned ON
RENODE > gpioPortA.UserLED State
RENODE < True
// Set UserLED Port to high level again
UART > led on
// Check that LED is turned ON
RENODE > gpioPortA.UserLED State
RENODE < False

Expected result: gpioPortA.UserLED State should return True
Observed result: gpioPortA.UserLED State return False

The problem is in the Renode implementation of the GPIO emulator for STM32:
[renode-infrastructure/STM32_GPIOPort.cs at 2894123d5ed5769ef1ba17e4ac6bc083c8931820 · renode/renode-infrastructure](https://github.com/renode/renode-infrastructure/blob/2894123d5ed5769ef1ba17e4ac6bc083c8931820/src/Emulator/Peripherals/Peripherals/GPIOPort/STM32_GPIOPort.cs)
```
{(long)Registers.BitReset, new DoubleWordRegister(this)
                    .WithValueField(0, 16, FieldMode.Write, 
                        writeCallback: (_, val) => { if(val != 0) WriteState((ushort)(BitHelper.GetValueFromBitsArray(State) ^ val)); },
                        name: "GPIOx_BRR")
                    .WithReservedBits(16, 16)
                },

```
The problem is with the bitwise operation "^" (exclusive or).

According to the description for this register:
![image](https://user-images.githubusercontent.com/107510113/173684662-032d9e04-90b2-428a-8aba-4edb05817687.png)

For any initial state of the bit, we must reset it to zero. Exclusive OR in this case will not work as expected, for example: pin state 0, reset bit 1. In this case, the state will be 1. Although it should be 0!

The correct operation is masking the reset bits and the bitwise AND operation (like it was made for similar issue in the BSRR register: https://github.com/renode/renode-infrastructure/commit/78527f6dea1ed838a23c52cd04bdd05ec62f6d81 ):

```
{(long)Registers.BitReset, new DoubleWordRegister(this)
                    .WithValueField(0, 16, FieldMode.Write, 
                        writeCallback: (_, val) => { if(val != 0) WriteState((ushort)(BitHelper.GetValueFromBitsArray(State) & ~val)); },
                        name: "GPIOx_BRR")
                    .WithReservedBits(16, 16)
                },
```

**Comment by MateuszKarlic** [comment]
Thanks for reporting the issue @dkDeman, this is now fixed upstream.
