### ISSUE TITLE
MC3635

### ISSUE THREAD

**Issue by Lerqiu** [renode/renode#346]
Hello,

I found small error with MC3635 sensor.
Based on datasheets  two last bits of register 0x20 should have value 0b01 not 0b10.

[MC3635_DriveMotionX ](https://github.com/renode/renode-infrastructure/blob/1a009faabbc6d219b940d07ef6432b187f12a59b/src/Emulator/Peripherals/Peripherals/Sensors/MC3635.cs#L548)

**Comment by JakubJatczak** [comment]
Hi @Lerqiu, thanks for pointing it out. I have just pushed a fix at c71aaaa.
Good catch :)
