### ISSUE TITLE
How can I increase the size of the Renode spawned terminal? I can barley see it on my display

### ISSUE THREAD

**Issue by John15321** [renode/renode#356]
Hi sorry this may seem like a dumb issue but on my display, I can barely see the text in the Renode terminal

Is there a way to increase it?

**Comment by PiotrZierhoffer** [comment]
Actually, there is! Look for the Renode config file: on Linux it's ~/.config/renode/config - you'll have an option to change the window and going font size.

**Comment by John15321** [comment]
> Actually, there is! Look for the Renode config file: on Linux it's ~/.config/renode/config - you'll have an option to change the window and going font size.

It worked! Thanks, I can finally see something 😁
