### ISSUE TITLE
HiFive Unleashed boot issue.

### ISSUE THREAD

**Issue by paulq11** [renode/renode#36]
Both win10 and Mac show the same issue when starting hifive_unleashed. 
Starting the resc file...

![image](https://user-images.githubusercontent.com/8881528/59531366-c3655900-8eb3-11e9-95cc-678fda04307e.png)

UART window ...
![image](https://user-images.githubusercontent.com/8881528/59531434-eb54bc80-8eb3-11e9-9216-d7221e022ee7.png)

userid=root
password=sifive

or password=<empty>

**Comment by PiotrZierhoffer** [comment]
Please try to log in with root/root and let us know if it helps

**Comment by paulq11** [comment]
yes - that did it. 
Thank you.
