### ISSUE TITLE
[question] How to Initialize Ethernet Adapter for Linux VexRISCV?

### ISSUE THREAD

**Issue by thesaadmemon** [renode/renode#366]
I recently started using the renode, and was wondering 

1. How can I connect various Linux instances for intercommunication? On booting with the given rootfs file, it prompts as follows"

'Starting network: ip: socket: Function not implemented
ip: socket: Function not implemented
FAIL'

Screenshot: -
![memon](https://user-images.githubusercontent.com/20953709/183707604-d8adbed0-9f61-4e49-a629-427ab7c9bf62.png)

- > I also added the "ethernet adapter" @platforms/CPUs/litex_vexriscv_linux.repl file manually, and here's how it looks like: 

Screenshot: -

![memon2](https://user-images.githubusercontent.com/20953709/183708618-8fc3545a-b00e-4944-a8db-28a102e95c0b.png)

Is there any way to get the ethernet adapter to get initialized with some random IP address within the Linux, and somehow it can communicate with the outside world?

Any help will be highly appreciated. 
Thanks in advance.

**Comment by MateuszKarlic** [comment]
Hi @thesaadmemon,

The demo you are running targets older kernel version without the networking support enabled.  We plan on updating it in the future, but for now you could either use a different demo with the kernel that has the support (`scripts/single-node/litex_vexriscv_sdcard.resc`), or build a new kernel and rootfs instead, as described here: https://github.com/renode/renode/issues/374#issuecomment-1254859841.

After building, you can use `litex_json2renode.py` from https://github.com/enjoy-digital/litex to generate a new platform description (repl), which will automatically include an Ethernet adapter. Then you should be able to use the adapter.

**Comment by PiotrZierhoffer** [comment]
Closing for now. Feel free to add a comment if you want to discuss this further.
