### ISSUE TITLE
Support MDIO with LiteEth 

### ISSUE THREAD

**Issue by mithro** [renode/renode#37]
From Wikipedia - [MDIO](https://en.wikipedia.org/wiki/Management_Data_Input/Output)
> Management Data Input/Output (MDIO), also known as Serial Management Interface (SMI) or Media Independent Interface Management (MIIM), is a serial bus defined for the Ethernet family of IEEE 802.3 standards for the Media Independent Interface, or MII. The MII connects Media Access Control (MAC) devices with Ethernet physical layer (PHY) circuits. The MAC device controlling the MDIO is called the Station Management Entity (SME).

Currently when Renode is emulating LiteEth it is also not emulating the MDIO interface. This means that the output from the example here -> https://github.com/timvideos/litex-buildenv/wiki/Renode shows the following output;
```
         built: Jun 14 2019 09:49:25
        uptime: 00:00:00
-----------------------------------------------
MDIO mode: 10Mbps / link: down
uIP init done with ip 192.168.100.50
Etherbone listening on port 1234
```

The issue being the `MDIO mode: 10Mbps / link: down` when it should probably `100Mbps / link: up`.

The firmware code which talks to the MDIO device can be found here;
 * [mdio.h](https://github.com/timvideos/litex-buildenv/blob/master/firmware/mdio.h)
 * [mdio.c](https://github.com/timvideos/litex-buildenv/blob/master/firmware/mdio.c)

There is some code for MDIO emulation in QEmu @ https://github.com/stffrdhrn/qemu/compare/master...mithro:mdio

**Comment by mateusz-holenko** [comment]
The support for MDIO in LiteX Ethernet is merged to master.
