### ISSUE TITLE
Renode needs a very short buffer time between each read/write. 

### ISSUE THREAD

**Issue by EuniceMadya** [renode/renode#375]
Thanks for taking the time to file an issue for Renode!

Please familiarize yourself with our [Contributing guidelines](https://github.com/renode/renode/blob/master/CONTRIBUTING.rst) first.

# Description

HPSHostController socket needs some buffer time to flush the output.

# Expected behaviour

# How to reproduce?

Not reproducable from Antmicro's end, but we have a fix. 

# Environment

Linux Ubuntu

# Do you plan to address this issue and file a PR?

Yes, it's a one-liner.

**Comment by mateusz-holenko** [comment]
This has been addressed in https://github.com/renode/renode-infrastructure/pull/73 and merged upstream in cdfd035f1b49c89803163bdc6f1baa9f977dabbb.
