### ISSUE TITLE
Request for adding STM32L452 support

### ISSUE THREAD

**Issue by dtran11** [renode/renode#408]
Are there any plans to support STM32L4 series? thank you

**Comment by PiotrZierhoffer** [comment]
Hi @dtran11 

We don't have specific plans for L4s, but please take a look at our Zephyr Dashboard: https://zephyr-dashboard.renode.io/

You will find L4 targets built and running sample Zephyr software.

![image](https://user-images.githubusercontent.com/1142698/204664047-06680134-2cd6-4068-aaf4-ad96ab43ce78.png)

If you click on the board name, you will be redirected to Renodepedia, and in the "Hardware" tab look for the "Renode dts2repl" button, it will give you the platform file usable by Renode.

![image](https://user-images.githubusercontent.com/1142698/204664231-f30bab03-c0c6-4e28-866d-88f030931dce.png)

**Comment by dtran11** [comment]
> Hi @dtran11
> 
> We don't have specific plans for L4s, but please take a look at our Zephyr Dashboard: https://zephyr-dashboard.renode.io/
> 
> You will find L4 targets built and running sample Zephyr software.
> 
> ![image](https://user-images.githubusercontent.com/1142698/204664047-06680134-2cd6-4068-aaf4-ad96ab43ce78.png)
> 
> If you click on the board name, you will be redirected to Renodepedia, and in the "Hardware" tab look for the "Renode dts2repl" button, it will give you the platform file usable by Renode.
> 
> ![image](https://user-images.githubusercontent.com/1142698/204664231-f30bab03-c0c6-4e28-866d-88f030931dce.png)

Thank you

**Comment by PiotrZierhoffer** [comment]
I'll close the issue for now, feel free to open new ones if you have other questions
