### ISSUE TITLE
Fedora package fails transaction check

### ISSUE THREAD

**Issue by tknapstad** [renode/renode#41]
I don't know if this is an fpm issue, but dnf on Fedora 30 detects packaging conflicts when attempting to install. A lot of other packages install icons into these folders without conflicts.

> Error: Transaction check error:
  file /usr/share/icons/hicolor from install of renode-1.8.0+20190902git20754cd-1.f23.x86_64 conflicts with file from package hicolor-icon-theme-0.17-5.fc30.noarch
  file /usr/share/icons/hicolor/128x128 from install of renode-1.8.0+20190902git20754cd-1.f23.x86_64 conflicts with file from package hicolor-icon-theme-0.17-5.fc30.noarch
  file /usr/share/icons/hicolor/128x128/apps from install of renode-1.8.0+20190902git20754cd-1.f23.x86_64 conflicts with file from package hicolor-icon-theme-0.17-5.fc30.noarch
  file /usr/share/icons/hicolor/16x16 from install of renode-1.8.0+20190902git20754cd-1.f23.x86_64 conflicts with file from package hicolor-icon-theme-0.17-5.fc30.noarch
  file /usr/share/icons/hicolor/16x16/apps from install of renode-1.8.0+20190902git20754cd-1.f23.x86_64 conflicts with file from package hicolor-icon-theme-0.17-5.fc30.noarch
  file /usr/share/icons/hicolor/24x24 from install of renode-1.8.0+20190902git20754cd-1.f23.x86_64 conflicts with file from package hicolor-icon-theme-0.17-5.fc30.noarch
  file /usr/share/icons/hicolor/24x24/apps from install of renode-1.8.0+20190902git20754cd-1.f23.x86_64 conflicts with file from package hicolor-icon-theme-0.17-5.fc30.noarch
  file /usr/share/icons/hicolor/32x32 from install of renode-1.8.0+20190902git20754cd-1.f23.x86_64 conflicts with file from package hicolor-icon-theme-0.17-5.fc30.noarch
  file /usr/share/icons/hicolor/32x32/apps from install of renode-1.8.0+20190902git20754cd-1.f23.x86_64 conflicts with file from package hicolor-icon-theme-0.17-5.fc30.noarch
  file /usr/share/icons/hicolor/48x48 from install of renode-1.8.0+20190902git20754cd-1.f23.x86_64 conflicts with file from package hicolor-icon-theme-0.17-5.fc30.noarch
  file /usr/share/icons/hicolor/48x48/apps from install of renode-1.8.0+20190902git20754cd-1.f23.x86_64 conflicts with file from package hicolor-icon-theme-0.17-5.fc30.noarch
  file /usr/share/icons/hicolor/64x64 from install of renode-1.8.0+20190902git20754cd-1.f23.x86_64 conflicts with file from package hicolor-icon-theme-0.17-5.fc30.noarch
  file /usr/share/icons/hicolor/64x64/apps from install of renode-1.8.0+20190902git20754cd-1.f23.x86_64 conflicts with file from package hicolor-icon-theme-0.17-5.fc30.noarch
  file /usr/share/icons/hicolor/scalable from install of renode-1.8.0+20190902git20754cd-1.f23.x86_64 conflicts with file from package hicolor-icon-theme-0.17-5.fc30.noarch
  file /usr/share/icons/hicolor/scalable/apps from install of renode-1.8.0+20190902git20754cd-1.f23.x86_64 conflicts with file from package hicolor-icon-theme-0.17-5.fc30.noarch
  file /usr/share/icons/hicolor from install of renode-1.8.0+20190902git20754cd-1.f23.x86_64 conflicts with file from package fedora-logos-30.0.2-1.fc30.x86_64
  file /usr/share/icons/hicolor/16x16 from install of renode-1.8.0+20190902git20754cd-1.f23.x86_64 conflicts with file from package fedora-logos-30.0.2-1.fc30.x86_64
  file /usr/share/icons/hicolor/16x16/apps from install of renode-1.8.0+20190902git20754cd-1.f23.x86_64 conflicts with file from package fedora-logos-30.0.2-1.fc30.x86_64
  file /usr/share/icons/hicolor/24x24 from install of renode-1.8.0+20190902git20754cd-1.f23.x86_64 conflicts with file from package fedora-logos-30.0.2-1.fc30.x86_64
  file /usr/share/icons/hicolor/24x24/apps from install of renode-1.8.0+20190902git20754cd-1.f23.x86_64 conflicts with file from package fedora-logos-30.0.2-1.fc30.x86_64
  file /usr/share/icons/hicolor/32x32 from install of renode-1.8.0+20190902git20754cd-1.f23.x86_64 conflicts with file from package fedora-logos-30.0.2-1.fc30.x86_64
  file /usr/share/icons/hicolor/32x32/apps from install of renode-1.8.0+20190902git20754cd-1.f23.x86_64 conflicts with file from package fedora-logos-30.0.2-1.fc30.x86_64
  file /usr/share/icons/hicolor/48x48 from install of renode-1.8.0+20190902git20754cd-1.f23.x86_64 conflicts with file from package fedora-logos-30.0.2-1.fc30.x86_64
  file /usr/share/icons/hicolor/48x48/apps from install of renode-1.8.0+20190902git20754cd-1.f23.x86_64 conflicts with file from package fedora-logos-30.0.2-1.fc30.x86_64
  file /usr/share/icons/hicolor/scalable from install of renode-1.8.0+20190902git20754cd-1.f23.x86_64 conflicts with file from package fedora-logos-30.0.2-1.fc30.x86_64
  file /usr/share/icons/hicolor/scalable/apps from install of renode-1.8.0+20190902git20754cd-1.f23.x86_64 conflicts with file from package fedora-logos-30.0.2-1.fc30.x86_64

**Comment by PiotrZierhoffer** [comment]
This should be fixed with 70c67e9
