### ISSUE TITLE
logFile output not the same as console output

### ISSUE THREAD

**Issue by mkschreder** [renode/renode#413]
### Description

Is there a standard way to display function name profiling data? I was thinking to add a python script that can extract function name data from the log when "LogFunctionNames" is enabled, but I ran into a problem. 

The problem is that the log file does not contain precise timing data like the console output. I could of course run renode through "tee" or something and then use the output of that as raw input to a python script, but isn't this a bug though:

![image](https://user-images.githubusercontent.com/4483721/204777285-57a55886-aa20-42dd-9680-18e8fbf9337a.png)

Shouldn't the outputs actually be identical? How come there no millisecond data in the log file?

### Expected behaviour

logFile output should have millisecond data.

**Comment by PiotrZierhoffer** [comment]
Fixed in c87c852

**Comment by PiotrZierhoffer** [comment]
If you still see there's an issue on your side, please reopen/file a new issue. Closing for now.
