### ISSUE TITLE
Using device tree instead of the platform description language

### ISSUE THREAD

**Issue by mkschreder** [renode/renode#419]
What about using the device tree format for platform description?

I believe it should be able to support all currently available features of the platform description syntax (and more).

It could potentially add much more standardization to renode platform definitions.

The way this can potentially be implemented is by calling libfdt directly from C#

Have there been discussions about adding this feature at all?

**Comment by mithro** [comment]
Renode can generate a platform description from DeviceTree (https://opensource.antmicro.com/projects/dts2repl) - see https://zephyr-dashboard.renode.io/renodepedia/ for examples.

**Comment by mkschreder** [comment]
Thanks @mithro. How do you render a trace like the one on this page: https://zephyr-dashboard.renode.io/renodepedia/boards/hexiwear_k64/?view=software&demo=Hello_World#colab

**Comment by mithro** [comment]
@PiotrZierhoffer might know.

**Comment by PiotrZierhoffer** [comment]
@mkschreder that's `cpu EnableProfiler`

Full documentation of the feature is here: https://renode.readthedocs.io/en/latest/advanced/execution-tracing.html#guest-application-profiling

In Renodepedia we use Speedscope traces.
