### ISSUE TITLE
Unable to reach network interface on polarfire icicle

### ISSUE THREAD

**Issue by sand7000** [renode/renode#439]
### Description

Unable to reach network interface on polarfire icicle board using provided demo script

### Expected behavior

I expected to be able to ping the interface on the IP it claims is up.

### How to reproduce?

In terminal:

```
sudo ip tuntap add mode tap tap0
sudo ip addr add 172.16.0.1/24 dev tap0
sudo ip link set tap0 up
sudo ip route add 172.16.0.0/24 via 172.16.0.1 dev tap0
renode
```
Then in renode:

```
emulation CreateTap "tap0" "tap"
start @scripts/single-node/polarfire-soc.resc
```

The window that comes up claims the board is listening on 172.16.0.3 but it is not reachable. I see the following in the terminal:
                                                                                                              

> 09:28:00.4915 [INFO] Loaded monitor commands from: /opt/renode/scripts/monitor.py
> 09:28:33.5152 [INFO] Opened interface tap0.                                                                                                   
> 09:29:58.4068 [INFO] Including script: /opt/renode/scripts/single-node/polarfire-soc.resc                                                     
> 09:29:58.4728 [INFO] System bus created.                                                                                                      
> 09:30:05.4378 [INFO] sysbus: Loading segment of 978944 bytes length at 0x8000000.                                                             
> 09:30:05.4534 [INFO] e51: Setting PC value to 0x8000000.                                                                                      
> 09:30:05.4535 [INFO] u54_1: Setting PC value to 0x8000000.                                                                                    
> 09:30:05.4536 [INFO] u54_2: Setting PC value to 0x8000000.                                                                                    
> 09:30:05.4537 [INFO] u54_3: Setting PC value to 0x8000000.                                                                                    
> 09:30:05.4538 [INFO] u54_4: Setting PC value to 0x8000000.                                                                                    
> 09:30:05.5075 [INFO] machine-0: Machine started.                                                                                              
> 09:30:05.5940 [WARNING] sysbus: [e51: 0x8001D7C] WriteDoubleWord to non existing peripheral at 0x20002084, value 0xFFFFFFFF.                  
> 09:30:05.5950 [WARNING] sysbus: [e51: 0x8001D9E] ReadQuadWord from non existing peripheral at 0x20005400.                                     
> 09:30:05.5953 [WARNING] sysbus: [e51: 0x8001DA8] WriteQuadWord to non existing peripheral at 0x20005400, value 0x1FF.                         
> 09:30:05.5957 [WARNING] sysbus: [e51: 0x8001DB4] WriteByte to non existing peripheral at 0x20005407, value 0x19.                              
> 09:30:05.5958 [WARNING] sysbus: [e51: 0x8001DD8] ReadQuadWord from non existing peripheral at 0x20005408.                                     
> 09:30:05.5959 [WARNING] sysbus: [e51: 0x8001DE2] WriteQuadWord to non existing peripheral at 0x20005408, value 0x203FFFF.                     
> 09:30:05.5959 [WARNING] sysbus: [e51: 0x8001DEE] WriteByte to non existing peripheral at 0x2000540F, value 0x1B.                              
> 09:30:05.5962 [WARNING] sysbus: [e51: 0x8001DFA] ReadDoubleWord from non existing peripheral at 0x20005D00.                                   
> 09:30:05.5963 [WARNING] sysbus: [e51: 0x8001E0A] WriteDoubleWord to non existing peripheral at 0x20005D00, value 0x7F80.                      
> 09:30:05.5963 [WARNING] sysbus: [e51: 0x8001E14] ReadDoubleWord from non existing peripheral at 0x20005D04.                                   
> 09:30:05.5964 [WARNING] sysbus: [e51: 0x8001E20] WriteDoubleWord to non existing peripheral at 0x20005D04, value 0x7000.                      
> 09:30:05.5965 [WARNING] sysbus: [e51: 0x8001E2A] ReadDoubleWord from non existing peripheral at 0x20005E08.                                   
> 09:30:05.5965 [WARNING] sysbus: [e51: 0x8001E3A] WriteDoubleWord to non existing peripheral at 0x20005E08, value 0x7F40.                      
> 09:30:05.5966 [WARNING] sysbus: [e51: 0x8001E44] ReadDoubleWord from non existing peripheral at 0x20005E0C.                                   
> 09:30:05.5966 [WARNING] sysbus: [e51: 0x8001E54] WriteDoubleWord to non existing peripheral at 0x20005E0C, value 0x6C00.                      
> 09:30:05.5967 [WARNING] sysbus: [e51: 0x8001E5E] ReadDoubleWord from non existing peripheral at 0x20005E10.                                   
> 09:30:05.5968 [WARNING] sysbus: [e51: 0x8001E6E] WriteDoubleWord to non existing peripheral at 0x20005E10, value 0x7F30.                      
> 09:30:05.5968 [WARNING] sysbus: [e51: 0x8001E78] ReadDoubleWord from non existing peripheral at 0x20005E14.                                   
> 09:30:05.5969 [WARNING] sysbus: [e51: 0x8001E88] WriteDoubleWord to non existing peripheral at 0x20005E14, value 0x6800.                      
> 09:30:05.6141 [WARNING] plic: Unhandled write to offset 0x2EC, value 0x0.                                                                     
> 09:30:05.6141 [WARNING] plic: Unhandled write to offset 0x200000, value 0x0.                                                                  
> 09:30:05.6154 [WARNING] mmuart0: Unsupported read from RZI configuration register at offset 0x34.                                             
> 09:30:05.6154 [WARNING] mmuart0: Unsupported write to RZI mode configuration register at offset 0x34.                                         
> 09:30:05.6154 [WARNING] mmuart0: Unsupported read from RZI configuration register at offset 0x34.                                             
> 09:30:05.6154 [WARNING] mmuart0: Unsupported write to RZI mode configuration register at offset 0x34.                                         
> 09:30:05.6155 [WARNING] mmuart0: Unsupported read from multi-mode configuration register at offset 0x38.                                      
> 09:30:05.6155 [WARNING] mmuart0: Unsupported write to multi-mode configuration register at offset 0x38.                                       
> 09:30:05.6155 [WARNING] mmuart0: Unsupported read from LIN configuration register at offset 0x30.                                             
> 09:30:05.6155 [WARNING] mmuart0: Unsupported write to LIN mode configuration register at offset 0x30.                                         
> 09:30:05.6156 [WARNING] mmuart0: Unsupported read from LIN configuration register at offset 0x30.                                             
> 09:30:05.6156 [WARNING] mmuart0: Unsupported write to LIN mode configuration register at offset 0x30.                                         
> 09:30:05.6156 [WARNING] mmuart0: Unsupported read from LIN configuration register at offset 0x30.                                             
> 09:30:05.6156 [WARNING] mmuart0: Unsupported write to LIN mode configuration register at offset 0x30.                                         
> 09:30:05.6156 [WARNING] mmuart0: Unsupported read from multi-mode configuration register at offset 0x38.                                      
> 09:30:05.6157 [WARNING] mmuart0: Unsupported write to multi-mode configuration register at offset 0x38.                                       
> 09:30:05.6157 [WARNING] mmuart0: Unsupported write to configuration register at offset 0x44.                                                  
> 09:30:05.6158 [WARNING] mmuart0: Unsupported write to multi-mode configuration register at offset 0x48.                                       
> 09:30:05.6159 [WARNING] mmuart0: Unsupported write to multi-mode configuration register at offset 0x4C.                                       
> 09:30:05.6160 [WARNING] mmuart0: Unsupported read from LIN configuration register at offset 0x30.                                             
> 09:30:05.6161 [WARNING] mmuart0: Unsupported write to LIN mode configuration register at offset 0x30.                                         
> 09:30:05.6161 [WARNING] mmuart0: Unsupported write to configuration register at offset 0x3C.                                                  
> 09:30:05.6161 [WARNING] mmuart0: Unsupported read from LIN configuration register at offset 0x30.                                             
> 09:30:05.6161 [WARNING] mmuart0: Unsupported write to LIN mode configuration register at offset 0x30.                                         
> 09:30:05.6162 [WARNING] mmuart0: Unsupported read from RZI configuration register at offset 0x34.                                             
> 09:30:05.6162 [WARNING] mmuart0: Unsupported write to RZI mode configuration register at offset 0x34.                                         
> 09:30:05.6162 [WARNING] mmuart0: Unsupported read from multi-mode configuration register at offset 0x38.                                      
> 09:30:05.6162 [WARNING] mmuart0: Unsupported write to multi-mode configuration register at offset 0x38.                                       
> 09:30:05.6349 [WARNING] sysbus: [e51: 0x8021BAC] ReadDoubleWord from non existing peripheral at 0x20002088.                                   
> 09:30:05.6349 [WARNING] sysbus: [e51: 0x8021BC2] WriteDoubleWord to non existing peripheral at 0x20002088, value 0x0.                         
> 09:30:05.6349 [WARNING] sysbus: [e51: 0x8021BCA] ReadDoubleWord from non existing peripheral at 0x20002088.                                   
> 09:30:05.6349 [WARNING] sysbus: [e51: 0x8021BE0] WriteDoubleWord to non existing peripheral at 0x20002088, value 0x0.                         
> 09:30:05.6351 [WARNING] sysbus: [e51: 0x8006462] ReadDoubleWord from non existing peripheral at 0x20002088.                                   
> 09:30:05.6351 [WARNING] sysbus: [e51: 0x8006474] WriteDoubleWord to non existing peripheral at 0x20002088, value 0x200000.                    
> 09:30:05.6352 [WARNING] sysbus: [e51: 0x80064FE] ReadDoubleWord from non existing peripheral at 0x20002088.                                   
> 09:30:05.6352 [WARNING] sysbus: [e51: 0x8006512] WriteDoubleWord to non existing peripheral at 0x20002088, value 0x0.                         
> 09:30:05.6402 [WARNING] gpio1: Unhandled write to offset 0x0. Unhandled bits: [2] when writing value 0x5. Tags: OutputBufferEnable (0x1).     
> 09:30:05.6402 [WARNING] gpio1: Unhandled write to offset 0x4. Unhandled bits: [2] when writing value 0x5. Tags: OutputBufferEnable (0x1).     
> 09:30:05.6404 [WARNING] gpio1: Unhandled write to offset 0x8. Unhandled bits: [2] when writing value 0x5. Tags: OutputBufferEnable (0x1).     
> 09:30:05.6404 [WARNING] gpio1: Unhandled write to offset 0xC. Unhandled bits: [2] when writing value 0x5. Tags: OutputBufferEnable (0x1).     
> 09:30:05.6404 [WARNING] gpio1: Unhandled write to offset 0x10. Unhandled bits: [2] when writing value 0x5. Tags: OutputBufferEnable (0x1).    
> 09:30:05.6406 [WARNING] gpio1: Unhandled write to offset 0x14. Unhandled bits: [2] when writing value 0x5. Tags: OutputBufferEnable (0x1).    
> 09:30:05.6406 [WARNING] gpio1: Unhandled write to offset 0x18. Unhandled bits: [2] when writing value 0x5. Tags: OutputBufferEnable (0x1).    
> 09:30:06.1634 [WARNING] sysbus: [e51: 0x8006496] ReadDoubleWord from non existing peripheral at 0x20002088.                                   
> 09:30:06.1636 [WARNING] sysbus: [e51: 0x80064A8] WriteDoubleWord to non existing peripheral at 0x20002088, value 0x400000.                    
> 09:30:06.1638 [WARNING] sysbus: [e51: 0x8006534] ReadDoubleWord from non existing peripheral at 0x20002088.                                   
> 09:30:06.1640 [WARNING] sysbus: [e51: 0x8006548] WriteDoubleWord to non existing peripheral at 0x20002088, value 0x0.                         
> 09:30:06.1644 [WARNING] gpio2: Unhandled write to offset 0x0. Unhandled bits: [2] when writing value 0x5. Tags: OutputBufferEnable (0x1).     
> 09:30:06.1646 [WARNING] gpio2: Unhandled write to offset 0x4. Unhandled bits: [2] when writing value 0x5. Tags: OutputBufferEnable (0x1).     
> 09:30:06.1648 [WARNING] gpio2: Unhandled write to offset 0x8. Unhandled bits: [2] when writing value 0x5. Tags: OutputBufferEnable (0x1).     
> 09:30:06.1651 [WARNING] gpio2: Unhandled write to offset 0xC. Unhandled bits: [2] when writing value 0x5. Tags: OutputBufferEnable (0x1).     
> 09:30:06.1653 [WARNING] gpio2: Unhandled write to offset 0x10. Unhandled bits: [2] when writing value 0x5. Tags: OutputBufferEnable (0x1).    
> 09:30:06.1655 [WARNING] gpio2: Unhandled write to offset 0x14. Unhandled bits: [2] when writing value 0x5. Tags: OutputBufferEnable (0x1).    
> 09:30:06.1657 [WARNING] gpio2: Unhandled write to offset 0x18. Unhandled bits: [2] when writing value 0x5. Tags: OutputBufferEnable (0x1).    
> 09:30:06.4268 [WARNING] sysbus: [e51: 0x8006496] ReadDoubleWord from non existing peripheral at 0x20002088.                                   
> 09:30:06.4269 [WARNING] sysbus: [e51: 0x80064A8] WriteDoubleWord to non existing peripheral at 0x20002088, value 0x400000.                    
> 09:30:06.4269 [WARNING] sysbus: [e51: 0x8006534] ReadDoubleWord from non existing peripheral at 0x20002088.                                   
> 09:30:06.4269 [WARNING] sysbus: [e51: 0x8006548] WriteDoubleWord to non existing peripheral at 0x20002088, value 0x0.                         
> 09:30:06.6274 [WARNING] sysbus: [e51: 0x8006496] ReadDoubleWord from non existing peripheral at 0x20002088.                                   
> 09:30:06.6274 [WARNING] sysbus: [e51: 0x80064A8] WriteDoubleWord to non existing peripheral at 0x20002088, value 0x400000.                    
> 09:30:06.6275 [WARNING] sysbus: [e51: 0x8006534] ReadDoubleWord from non existing peripheral at 0x20002088.                                   
> 09:30:06.6275 [WARNING] sysbus: [e51: 0x8006548] WriteDoubleWord to non existing peripheral at 0x20002088, value 0x0.                         
> 09:30:06.6276 [WARNING] gpio2: Unhandled write to offset 0x0. Unhandled bits: [2] when writing value 0x5. Tags: OutputBufferEnable (0x1).     
> 09:30:06.6276 [WARNING] gpio2: Unhandled write to offset 0x4. Unhandled bits: [2] when writing value 0x5. Tags: OutputBufferEnable (0x1).     
> 09:30:06.6277 [WARNING] gpio2: Unhandled write to offset 0x8. Unhandled bits: [2] when writing value 0x5. Tags: OutputBufferEnable (0x1).     
> 09:30:06.6277 [WARNING] gpio2: Unhandled write to offset 0xC. Unhandled bits: [2] when writing value 0x5. Tags: OutputBufferEnable (0x1).     
> 09:30:06.6278 [WARNING] gpio2: Unhandled write to offset 0x10. Unhandled bits: [2] when writing value 0x5. Tags: OutputBufferEnable (0x1).    
> 09:30:06.6278 [WARNING] gpio2: Unhandled write to offset 0x14. Unhandled bits: [2] when writing value 0x5. Tags: OutputBufferEnable (0x1).    
> 09:30:06.6278 [WARNING] gpio2: Unhandled write to offset 0x18. Unhandled bits: [2] when writing value 0x5. Tags: OutputBufferEnable (0x1).    
> 09:30:06.8355 [WARNING] plic: Unhandled write to offset 0x2EC, value 0x0.                                                                     
> 09:30:06.8356 [WARNING] plic: Unhandled write to offset 0x200000, value 0x0.                                                                  
> 09:30:06.8419 [WARNING] sysbus: [e51: 0x8002C16] ReadDoubleWord from non existing peripheral at 0x20002084.                                   
> 09:30:06.8421 [WARNING] sysbus: [e51: 0x8002C24] WriteDoubleWord to non existing peripheral at 0x20002084, value 0x2.                         
> 09:30:06.8422 [WARNING] sysbus: [e51: 0x8002C2C] ReadDoubleWord from non existing peripheral at 0x20002088.                                   
> 09:30:06.8422 [WARNING] sysbus: [e51: 0x8002C3A] WriteDoubleWord to non existing peripheral at 0x20002088, value 0x2.                         
> 09:30:06.8422 [WARNING] sysbus: [e51: 0x8002C66] ReadDoubleWord from non existing peripheral at 0x20002088.                                   
> 09:30:06.8423 [WARNING] sysbus: [e51: 0x8002C72] WriteDoubleWord to non existing peripheral at 0x20002088, value 0x0.                         
> 09:30:06.8424 [WARNING] mac0: Unhandled write to offset 0xC, value 0x1.                                                                       
> 09:30:06.8436 [WARNING] mac0: Unhandled write to offset 0x0. Unhandled bits: [4-5, 16, 20] when writing value 0x110030. Tags: man_port_en (0x1), clear_all_stats_regs (0x1), pfc_enable (0x1), ptp_unicast_ena (0x1).                                                                       
> 09:30:06.8436 [WARNING] mac0: Unhandled write to offset 0x4. Unhandled bits: [1, 8, 10, 13, 16, 21, 23] whel_duplex (0x1), receive_1536_byte_frames (0x1), gigabit_mode_enable (0x1), pause_enable (0x1), length_fields_width (0x1), disable_copy_of_pause_frames (0x1).                                                         
> 09:30:06.8437 [WARNING] sysbus: [e51: 0x800359E] WriteDoubleWord to non existing peripheral at 0x4, value 0
> 09:30:06.8440 [WARNING] mac0: Unhandled read from offset 0x200.                                            
> 09:30:06.8440 [WARNING] mac0: Unhandled write to offset 0x200, value 0x8000.                               
> 09:30:06.8442 [WARNING] mac0: Unhandled write to offset 0x10. Unhandled bits: [2, 4, 7, 17, 21, 23] when wrburst_length (0x4), endian_swap_packet (0x1), rx_buf_size (0xA2).                                          
> 09:30:06.8444 [WARNING] mac0: Unhandled write to offset 0x4A0, value 0x18.                                 
> 09:30:06.8444 [WARNING] mac0: Unhandled write to offset 0x4A4, value 0x18.                                 
> 09:30:06.8444 [WARNING] mac0: Unhandled write to offset 0x4A8, value 0x18.                                 
> 09:30:06.8445 [WARNING] mac0: Unhandled write to offset 0x440, value 0x804AC71.                            
> 09:30:06.8445 [WARNING] mac0: Unhandled write to offset 0x444, value 0x804AC71.                            
> 09:30:06.8445 [WARNING] mac0: Unhandled write to offset 0x448, value 0x804AC71.                            
> 09:30:06.8446 [WARNING] mac0: Unhandled write to offset 0x480, value 0x804ACD1.                            
> 09:30:06.8446 [WARNING] mac0: Unhandled write to offset 0x484, value 0x804ACD1.                            
> 09:30:06.8447 [WARNING] mac0: Unhandled write to offset 0x488, value 0x804ACD1.                            
> 09:30:06.8447 [WARNING] mac0: Unhandled write to offset 0x48, value 0x2800.                                
> 09:30:06.8459 [WARNING] mac0: Unhandled write to offset 0x2C. Unhandled bits: [4-6, 8-31] when writing valu
> 09:30:06.8460 [WARNING] mac0: Unhandled write to offset 0x620, value 0xFFFFFFFF.                           
> 09:30:06.8460 [WARNING] mac0: Unhandled write to offset 0x624, value 0xFFFFFFFF.                           
> 09:30:06.8460 [WARNING] mac0: Unhandled write to offset 0x628, value 0xFFFFFFFF.                           
> 09:30:06.8461 [WARNING] mac0: Unhandled write to offset 0x90, value 0x0.                                   
> 09:30:06.8461 [WARNING] mac0: Unhandled write to offset 0x94, value 0x0.                                   
> 09:30:06.8461 [WARNING] mac0: Unhandled write to offset 0x98, value 0x0.                                   
> 09:30:06.8462 [WARNING] mac0: Unhandled write to offset 0x9C, value 0x0.                                   
> 09:30:06.8462 [WARNING] mac0: Unhandled write to offset 0xA0, value 0x0.                                   
> 09:30:06.8463 [WARNING] mac0: Unhandled write to offset 0xA4, value 0x0.                                   
> 09:30:06.8463 [WARNING] mac0: Unhandled write to offset 0x4. Unhandled bits: [1, 10] when writing value 0xAbit_mode_enable (0x1).                                                                                     
> 09:30:06.8468 [WARNING] mac0: Unhandled write to offset 0x28. Unhandled bits: [10-14] when writing value 0x
> 09:30:06.8470 [WARNING] mac0: Unhandled write to offset 0x28. Unhandled bits: [4-6, 9, 12-14, 30-31] when w
> 09:30:06.8470 [WARNING] mac0: Unhandled write to offset 0x600, value 0x7C86.                               
> 09:30:06.8471 [WARNING] mac0: Unhandled read from offset 0x600.                                            
> 09:30:06.8471 [WARNING] mac0: Unhandled write to offset 0x600, value 0xC0007270.                           
> 09:30:06.8471 [WARNING] mac0: Unhandled write to offset 0x604, value 0x7C86.                               
> 09:30:06.8472 [WARNING] mac0: Unhandled read from offset 0x604.                                            
> 09:30:06.8472 [WARNING] mac0: Unhandled write to offset 0x604, value 0xC0007270.                           
> 09:30:06.8473 [WARNING] mac0: Unhandled write to offset 0x608, value 0x7C86.                               
> 09:30:06.8473 [WARNING] mac0: Unhandled read from offset 0x608.                                            
> 09:30:06.8474 [WARNING] mac0: Unhandled write to offset 0x608, value 0xC0007270.         

### Environment

Please, provide the following information:

- OS: Ubuntu 20.04
- Renode version (with commit SHA) Renode, version 1.13.3.19119 (a72a1fa1-202302201037)

### Do you plan to address this issue and file a PR?

Support  appreciated

**Comment by podhrmic** [comment]
@sand7000 looks like the missing piece was setting up a switch and start the tap interface in renode:
```
(machine-0) connector Connect mac0 switch
(machine-0) emulation CreateTap "tap0" "tap"
(machine-0) connector Connect host.tap switch
(machine-0) host.tap Start
```

Then the example servers the web page as expected:
![Screenshot from 2023-03-08 12-12-39](https://user-images.githubusercontent.com/2790461/223838544-6c79af74-39f0-4e28-8adf-7a06b230c37d.png)
