### ISSUE TITLE
RCC_CR read access on stm32f103 platform

### ISSUE THREAD

**Issue by bjauny** [renode/renode#461]
### Description

Hey there, tipping my toes in Renode for now I'm trying to make a basic firmware work on a NUCLEO_F103RB from ST-Micro. The Renode platform basically uses the stm32f103.repl file with an additional button peripheral.

The firmware init is stuck on the clock setup. From what I see, stm32f103.repl defines a tag for read access to RCC_CR register, but this register shoud be able to change depending on PLL disable/enable requests (write requests to another register address).
I'm a bit lost on how this could be achieved. Should there be a full peripheral managing this behaviour?

### Usage example
Typically here are the logs I obtain when I run my example:

```
10:11:35.2917 [WARNING] sysbus: [cpu: 0x8000D1C] (tag: 'RCC_CR') ReadDoubleWord from non existing peripheral at 0x40021000, returning 0x0A020083.
[...]
10:14:36.1158 [WARNING] sysbus: [cpu: 0x8000FBA] WriteDoubleWord to non existing peripheral at 0x42420060, value 0x0.
10:15:29.0307 [WARNING] sysbus: [cpu: 0x8000D1C] (tag: 'RCC_CR') ReadDoubleWord from non existing peripheral at 0x40021000, returning 0x0A020083.
```

The first read is the default behaviour, made possible by the tag. Then, the firmware request the PLL to be disabled (the write of 0 to 0x42420060). This should make the RCC_CR be at 0 until we re-enable the PLL but due to the tag it keeps returning the default value.

**Comment by mateusz-holenko** [comment]
Hi @bjauny, thanks for opening an issue.

Renode is designed with the ability prototyping platforms fast in mind. This means it is prepared for running incomplete setups with lacking peripherals models or part of their logic.
Clock configuration is often a layer that we mock in platforms (as it's configured once during initialization and not that important from the Renode models perspective anyway). In this context RCC-like peripherals are often either omitted or handled in a form of tags or simple python devices (pydevs).

In your scenario it looks like the software is more demanding and requires to read the previously written value back. To achieve that you could either replace the tag (which is just a read-only static value) with a python device (take a look at https://github.com/renode/renode/blob/master/platforms/cpus/starfive-jh7100.repl#L38-L60 for reference) or a simple model written in C# (https://github.com/renode/renode-infrastructure/blob/master/src/Emulator/Peripherals/Peripherals/Miscellaneous/STM32F4_RCC.cs is an example, although you probably don't need to implement all the registers).

**Comment by bjauny** [comment]
Hi @mateusz-holenko , and thanks for the answer. The case is a bit more complex since the behavior I need to simulate is that a write in a peripheral changes the values in another peripheral. Typically writing at "non existing peripheral at 0x42420060" should change the value I read at "non existing peripheral at 0x40021000".

Can peripherals refer each other in a repl file? Or is this a logic only doable in C# models? I'll try to see what I can achieve with your hints though.

**Comment by bjauny** [comment]
After diving more in the various documentations, it appear the write operations on 0x42420060 are bit-band writes, who end up as an alias for writing in the RCC_CR register.
So I always target the same physical register, it's just that Renode sees this as a write to another peripheral (since it's a totally different address). Is there support for bitbanding?

**Comment by mateusz-holenko** [comment]
@bjauny Good to hear that your setup works fine in Renode.

For the record, it's possible to access a peripheral from another one - in such case we often just pass them via constructor parameters; the before-mentioned `STM32F4_RCC` is a good example here.

Closing for now, but feel free to open a new issue in case of future questions.
