### ISSUE TITLE
STM32G0B1 Emulator Crash - "Trying to execute code outside RAM"

### ISSUE THREAD

**Issue by ItamarEliakim-R** [renode/renode#474]
### Description
The emulator crashes when running a simple STM32G0B1 code.

### Expected behaviour
Expected to see a blinking led example and UART2 emulation.

### How to reproduce?
Simple STM32G0 code generated using CubeMX, including GPIO, and UART2.
The code crashes and raises the following error - 
cpu: CPU abort [PC=0x0]: Trying to execute code outside RAM or ROM at 0x00000000.

It seems that the execution isn't related to the HAL initialization, as same error occurs on an empty main function.

### Environment
Ubuntu 20.04
Renode, version 1.13.3.19119 (a72a1fa1-202302201037)

### Additional information
resc file - 
```
using sysbus
mach create
machine LoadPlatformDescription @platforms/cpus/stm32g0.repl
machine LoadPlatformDescription @platforms/boards/stm32g0b1re.repl
machine StartGdbServer 3333
showAnalyzer usart2
showAnalyzer usart1
peripherals
logLevel -1 sysbus.gpioPortC.Led2
logLevel -1 sysbus.gpioPortC.Led1
logLevel -1 sysbus.gpioPortC
logLevel -1
sysbus LogPeripheralAccess sysbus.gpioPortC
macro reset
"""
    sysbus LoadELF @STM32G0B1_Test.elf
"""
runMacro $reset
```

### Do you plan to address this issue and file a PR?
Yes

**Comment by Itamare4** [comment]
Link - https://github.com/Itamare4/renode-issue-reproduction-template

**Comment by PiotrZierhoffer** [comment]
Hi @Itamare4 , thanks for submitting the issue.

I believe you didn't provide your stm32g0.repl - can you please add it to the repo?

**Comment by ItamarEliakim-R** [comment]
Hi @PiotrZierhoffer,

Thanks.
The stm32g0.repl is the default one available here - https://github.com/renode/renode/blob/master/platforms/cpus/stm32g0.repl

**Comment by ItamarEliakim-R** [comment]
It seems that the codes fails somewhere around here - 
![image](https://github.com/renode/renode/assets/94830602/203de14b-aeeb-4cdd-8219-e9dd6cb86473)

@PiotrZierhoffer - Any idea?


Thanks

**Comment by electrodonkey** [comment]
hi @ItamarEliakim-R ,

did you have a look at 
`HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_0) != HAL_OK`

i suspect that you would need to mock some register value via TAG as described [here](https://renode.readthedocs.io/en/latest/advanced/writing-peripherals.html) in order to get that HAL_OK return value.

Kind regards,
Dan

**Comment by ItamarEliakim-R** [comment]
Hi @electrodonkey,

Apologies for being renode newbie :)
Found it, the issue was with the default initialization of the RCC repl on the STM32G0.
If you remove the RCC block from repl, and load the SVD - everything works properly.


Thank you all.
Itamar

**Comment by ItamarEliakim-R** [comment]
Hi @electrodonkey,

Apologies for being renode newbie :)
Found it, the issue was with the default initialization of the RCC repl on the STM32G0.
If you remove the RCC block from repl, and load the SVD - everything works properly.


Thank you all.
Itamar
