### ISSUE TITLE
Installer Localization: "Menu Start" -> "Start Menu"

### ISSUE THREAD

**Issue by xobs** [renode/renode#48]
In the EN(SG?) version of the Windows installer, there is a tickbox that says "Add shortcut to Menu Start".  This should read "Add shortcut to Start Menu".

![image](https://user-images.githubusercontent.com/238325/70828636-b73c6300-1e26-11ea-9b38-00e321316c93.png)

**Comment by PiotrZierhoffer** [comment]
Thanks for the report.

This is fixed on master with a8fa838, and will be part of the next release.
