### ISSUE TITLE
Supported Peripherals in documentation is impossible to read

### ISSUE THREAD

**Issue by sullivanmj** [renode/renode#482]
### Description

There is a problem with the [Supported Peripherals section on the Supported boards page in the docs](https://renode.readthedocs.io/en/latest/introduction/supported-boards.html#supported-peripherals). See near the bottom of this screenshot.

![image](https://github.com/renode/renode/assets/50746840/236eb269-96db-46b0-b2fc-2af4fb3c8e97)

### Expected behaviour

The section should be usable.

### How to reproduce?

Visit the page and click on a specific board/target.

### Environment

- OS: Windows 10 64-bit
- Renode version 5e7c6aa1
- Occurs in both:
  - Edge 114.0.1823.67 (Official build) (64-bit)
  - Chrome 114.0.5735.199 (Official Build) (64-bit) (cohort: Stable) 

### Additional information

None

### Do you plan to address this issue and file a PR?

No, this isn't a huge deal for me as I was able to find what I needed by browsing the source code.

**Comment by PiotrZierhoffer** [comment]
Fixed upstream, thanks for pointing it out
