### ISSUE TITLE
cpu command does not work

### ISSUE THREAD

**Issue by adamsanta** [renode/renode#489]
### Description

I want to profile an elf file. 
To do so, I want to run `cpu EnableProfilerCollapsedStack`.
But renode console is telling me: `No such command or device: cpu` and so does nothing.

### How to reproduce?

It seems hard to find a way to reproduce.

### Environment

I am on Ubuntu 22.04 running Renode v1.13.13.19119 (a72a1fa1-202302201037)

**Comment by PiotrZierhoffer** [comment]
Hi @adamsanta 

Thanks for reporting the issue.

I added a clarification, also referring to some additional reading, which I recommend going through first: https://renode.readthedocs.io/en/latest/basic/monitor-syntax.html#renode-script-syntax and https://renode.readthedocs.io/en/latest/basic/machines.html#accessing-and-manipulating-peripherals

The updated documentation is published.
