### ISSUE TITLE
Different robotframework versions pinned

### ISSUE THREAD

**Issue by pjonsson** [renode/renode#491]
### Description

Commit 5a59225 pins robotframework to 6.0.2, but `tools/packaging/conda/meta.yaml` pins it to 4.0.1.

### Expected behaviour

If the version is pinned, I would expect the same version of robotframework to be used everywhere.

### Environment

Latest main branch.

### Do you plan to address this issue and file a PR?

Do not plan to file a PR.

**Comment by PiotrZierhoffer** [comment]
This is fixed on master, thanks again
