### ISSUE TITLE
How to add a UART analyzer in Renode?

### ISSUE THREAD

**Issue by fdsgdshn** [renode/renode#505]
Hello, 

I'm quite new to Renode. I want to create a project for a different processor, for example, MSP430F5529, in Renode. Therefore, I want to create all peripheral components according to the documentation specific to this processor. For instance, I've created a .cs file for UART myself. I didn't encounter any issues when including it, but when I try to read messages with `showAnalyzer`, I receive a warning that no backend is found. The error message is as follows: 

**No backend found for sysbus.UART0' error while initializing analyzer for: sysbus.UART0. Are you missing a required plugin?** 

Do I need to create a backend file for this? I couldn't find any information about this on Renode's GitHub page. What do I need to do to read messages via UART using `showAnalyzer`? I would greatly appreciate it if you could provide me with some information. 

Thank you

**Comment by mateusz-holenko** [comment]
Hi @fdsgdshn, thanks for creating an issue.

It looks like you need to implement the[ `IUART` interface](https://github.com/renode/renode-infrastructure/blob/master/src/Emulator/Main/Peripherals/UART/IUART.cs) (or derive from the [UARTBase](https://github.com/renode/renode-infrastructure/blob/master/src/Emulator/Main/Peripherals/UART/UARTBase.cs) class). With this Renode should be able to automatically create a backend for your model and show the analyzer window.

**Comment by PiotrZierhoffer** [comment]
Closing this one, but if you see that adding IUART doesn't help - please reopen
