### ISSUE TITLE
About IRQController.NVIC & CPU.CortexM Classes

### ISSUE THREAD

**Issue by fdsgdshn** [renode/renode#523]
Hi, 

I had a code that previously worked in Renode. However, after updating the repository, I noticed that the project no longer functions. Indeed, when I go to the src/peripherals path, I see that the IRQControllers.NVIC extension is no longer present. What do I need to do to be able to use this IRQController? Can you provide some guidance?

nvic: IRQControllers.NVIC @ sysbus 0xE000E000
    priorityMask: 0xFF
    systickFrequency: 120000000
    IRQ -> cpu@0
    cpuId: 0x410FC241

cpu: CPU.CortexM @ sysbus
    cpuType: "cortex-m4"
    nvic: nvic

Error message: 
Error E25: Could not find suitable constructor for type 'Antmicro.Renode.Peripherals.IRQControllers.NVIC'.
Constructor selection report:
Considering ctor Antmicro.Renode.Peripherals.IRQControllers.NVIC with the following parameters: [Antmicro.Renode.Core.IMachine, System.Int64 (optional), System.Byte (optional), System.
Boolean (optional)].
  Parameter 'machine' of type 'Antmicro.Renode.Core.IMachine' filled with default value = 'machine'.
  

Thank you very much.
Best regards.

**Comment by mateusz-holenko** [comment]
Hi @fdsgdshn, thanks for reporting the issue.

Recent changes to the NVIC model (https://github.com/renode/renode-infrastructure/commit/212ff2eebaf75bdddfb075fb2391b00a389d4a22) removed the `cpuId` property - it's now automatically taken from the CPU object itself (please note, that it might not be the same value as you used to provide - question if that's an issue in your case?).

The simplest solution for the error you observe is to remove the `cpuId: 0x410FC241` line from repl completely.
