### ISSUE TITLE
How get/set a program variable when running robot

### ISSUE THREAD

**Issue by nandojve** [renode/renode#543]
### Description

Assuming that there is a `bss.my_var` available in the `*.elf` file how I can get access to the content of that variable.

### Usage example

The intention is using robot move program to a specific time and read/write in the variable.

* start app
* move time to X
* read/get the `bss.my_var` value
* take decision inside robot
* write/set a new value in the `bss.my_var`
* move execution to next time X+1

### Additional information

I imagine this could be something similar to `sysbus GetSymbolAddress "_vector_table"`

**Comment by MarWit** [comment]
Hey @nandojve!

You are right about relevance of `sysbus GetSymbolAddress <symbol-name>` — you can use that method to acquire address of any symbol located in the `.symtab` section (pretty much any _global_ symbol for that matter).

```
$myVarAddress=`sysbus GetSymbolAddress "my_var"`
```

Now you can read contents of this using appropriate `sysbus` method, e.g. assuming that variable in question is unsigned int, you could do:

```
sysbus ReadDoubleWord $myVarAddress
```

Other methods you would want to use are:
```
sysbus ReadByte <address> # reads single byte, returns as byte
sysbus ReadWord <address> # reads two bytes, returns as unsigned short
sysbus ReadDoubleWord <address> # reads four bytes, returns as unsigned int
sysbus ReadQuadWord <address> # reads four bytes, returns as unsigned long
sysbus ReadBytes <address> <count> # reads <count> bytes, returns as array of bytes
```

There are also dual `sysbus` methods for writes:

```
sysbus ReadByte <address> <value>
sysbus ReadWord <address> <value>
sysbus ReadDoubleWord <address> <value>
sysbus ReadQuadWord <address> <value>
```

So, lets assume that `my_var` is global, unsigned int; the robot test would look something like this:

```
*** Test Cases ***
Check If my_var Is Equal To Zero
                 Prepare Platform
                 # Store my_var address in Robot variable
${MY_VAR_ADDR}=  Execute Command    sysbus GetSymbolAddress "my_var"
                 # Move simulation by one second forward
                 Execute Command    emulation RunFor "00:00:01"
${MY_VAR}=       Execute Command    sysbus ReadDoubleWord ${MY_VAR_ADDR}
                 Should Be Equal    ${MY_VAR}    0    my_var should be equal to zero
```
