### ISSUE TITLE
How to Set Up External Interrupts for Mi-V RV32 in REPL Script?

### ISSUE THREAD

**Issue by ChaseWeimer** [renode/renode#579]
### Description

I am trying to emulate a Mi-V RV32 (PolarFire soft core Risc-V processor, emulated as CPU.RiscV32) design that has external system interrupts but no PLIC. I didn't see any examples available on that in particular, and despite digging through the Renode source code, I'm still not sure how to accomplish this. I went down a rabbit hole digging through how the interrupt system worked for that processor in Renode, and I think I've verified that support for external interrupts exist, but I just couldn't tell how to hook them up in my repl script file. And just to clarify, the interrupt lines I'm referring to aren't the default single external IRQ line. Rather, I'm talking about the 8 external system interrupt lines. See sections 2.4 and 4.12.3 of [the Mi-V RV32 user guide](https://ww1.microchip.com/downloads/aemDocuments/documents/FPGA/ProductDocuments/SupportingCollateral/MIV_RV32+v3.1+User+Guide.pdf) for details.

Could someone provide some guidance on how to connect to the external interrupt lines on the Mi-V RV32 to something like a GPIO line? 

Additionally, could you also provide advice on how I might be able to find this information for myself in the source code to aid in answering future questions I have? Are there lists of the available ports that are exposed in the source code that the repl file interpreter uses that are easily accessible?

Any help is much appreciated. Thanks in advance!

**Comment by mateusz-holenko** [comment]
Hi @ChaseWeimer, thanks for asking the question.

The generic `RiscV32` model supports standard `User/Supervisor/Hypervisor/Machine Software/Timer/External` interrupt signals as defined by the RISC-V specification.

In Renode it is possible to support other configuration of interrupt lines at CPU level as well, but this requires preparing a specific model.
For example take a look at `Minerva.cs` - it extends `OnGPIO` method and keeps track of all external interrupt lines in the `irqPending` field and exposes it via custom CSRs.
Please note that this might also require a different interpretation of IRQ lines at tlib-level (e.g., to correctly calculate vector address).

For this CPU the meaning of IRQ lines 0, 1, 2 is different than for a standard RISC-V CPU, but the mechanism for connecting the in `repl` is exactly the same - see `litex_minerva.repl` as an example.
