### ISSUE TITLE
Adding external spi flash to nrf5340 (using Macronix_MX25R)

### ISSUE THREAD

**Issue by Prakasia** [renode/renode#600]
### Description
@PiotrZierhoffer 
Hi, 
I am trying to add a peripheral which is an external flash to nrf5340dk. I am using the zephyr sample spi_flash (replacing qspi with spi). And the sample is working in real hardware. 
When I try to do in renode nrf53 platform is not identifying the external flash. 
I used the peripheral available in renode repo Macronix_MX25R.cs . I know it is not completely implemented. So How can I model the peripheral in such a way that during the initialization external flash should be able to return the jedec_id to the platform? Any insight on how to modify the peripheral model will be useful. Because I am not so familiar with cs, 

### Usage example
[nrf5340repl.txt](https://github.com/renode/renode/files/15024620/nrf5340repl.txt)
[spi2_resc.txt](https://github.com/renode/renode/files/15024621/spi2_resc.txt)
![spi_issue](https://github.com/renode/renode/assets/123327474/09ce1389-13b0-484b-9398-722a5eece839)
It is not initialized since it is not able to get the jedec_id correctly.

### Additional information

I am using Renode, version 1.15.0.27975 (9111b18e-202403181532) in Ubuntu 22.04

**Comment by Prakasia** [comment]
Manged to figure it out. It was because dma was not enabled in platform file for spi. And made changes for the external peripheral to behave according to the requirements

**Comment by isimeonov14** [comment]
Hello @Prakasia, Do you have any idea of the I2C from the nrf52840 can also be implemented for the nrf5340, as you did for the SPI? Thank you, in advance!
