### ISSUE TITLE
Add command line display of `renode` version?

### ISSUE THREAD

**Issue by g40** [renode/renode#607]
Using a fresh install of `renode_1.9.0.msi` fails to run as expected. `

`--version` is unsupported and
`--help`  displays no salient version information.

Perhaps it should?

```
>renode --version
Unexpected options detected: --version

usage: Renode.exe [options] [script]
```

**Comment by Mes-ser** [comment]
I would recommend updating to newest version (1.15.0) where `--version`/`-v` is working.

**Comment by g40** [comment]
@PiotrZierhoffer @Mes-ser 

Thank you for the comments. Here, then, is a bit of a puzzle. I downloaded an installer via Github releases last night as you can see. Please note the version number! 

I will get the latest shortly.

BR 

Jerry.

![image](https://github.com/renode/renode/assets/812250/820b0a1b-4d20-43af-bb56-801ef480dde9)

**Comment by mgielda** [comment]
I think this can be safely closed, if I am misunderstanding anything, please reopen.
