### ISSUE TITLE
Trying to write to a disabled Tx

### ISSUE THREAD

**Issue by RYE2001** [renode/renode#614]
I am trying to create a project in Renode using an already created project on real Zedboard.
The project is a simple hello_world, i build the project and run it on Zedboard and it works just fine.
But when i tried to run the generated hello_world.elf in a Renode platform i get that "Trying to write to a disabled Tx"!!

any help would be great.
![bbbbb](https://github.com/renode/renode/assets/88210312/283fad8a-d085-4ab3-bf8f-3880d1a49b42)

**Comment by naitgacem** [comment]
Hello, have you been able to figure this out?
