### ISSUE TITLE
Read value from GPIO

### ISSUE THREAD

**Issue by Jocarfl** [renode/renode#630]
Hello,
I'm trying to read the value of a GPIO but without having to configure it as Miscellanneous.LED. Is there any other way to read the value without having to configure the peripheral as LED?

**Comment by JohnZhang3IoT** [comment]
using command from monitor, eg: in stm32f4, you can do this sysbus.gpioPortA GetGPIOs, then you can get this:
[
(0, GPIO: unset), (1, GPIO: unset), (2, GPIO: unset), (3, GPIO: unset), (4, GPIO: unset), (5
, GPIO: unset), (6, GPIO: unset), (7, GPIO: unset), (8, GPIO: unset), (9, GPIO: unset), 
(10, GPIO: unset), (11, GPIO: unset), (12, GPIO: unset), (13, GPIO: unset), (14, GPIO: unset
), (15, GPIO: unset), 
]
