### ISSUE TITLE
Feature Request: Ethernet Support for Cortex-A53 Linux in Renode

### ISSUE THREAD

**Issue by zxsoft** [renode/renode#633]
### Description

I am currently using the cortex-a53-linux.resc script in Renode, and I have noticed that Ethernet support is not included. I would like to understand whether I need to manually add Ethernet support to the script or if Ethernet support is currently not available for the Cortex-A53 Linux configuration in Renode.

My purpose is to run a mqtt client on linux which needs an ethernet device providing Internet connection.

### Usage example

s @scripts/single-node/cortex-a53-linux.resc
and then:

(ARM Cortex-A53) peripherals 
Available peripherals:
  sysbus (SystemBus)
  │   
  ├── bl31 (MappedMemory)
  │       <0x0E000000, 0x0EFFFFFF>
  │       
  ├── cpu (ARMv8A)
  │   │   Slot: 0
  │   │   
  │   └── timer (ARM_GenericTimer)
  │           
  ├── flash (MappedMemory)
  │       <0x00000000, 0x07FFFFFF>
  │       
  ├── gic (ARM_GenericInterruptController)
  │       <0x08000000, 0x0800FFFF> [region: distributor]
  │       <0x080A0000, 0x08FFFFFF> [region: redistributor]
  │       
  ├── ram (MappedMemory)
  │       <0x40000000, 0xBFFFFFFF>
  │       
  ├── rtc (PL031)
  │       <0x09010000, 0x09010FFF>
  │       
  └── uart0 (PL011)
          <0x09000000, 0x09000FFF>
          
(ARM Cortex-A53) 

So, I can't connect the machine to a switch which connected to a host "tap0" device.

### Additional information

I tried both version 1.14 and 1.15 , both linux and windows, neither provided a ethernet description in the ".repl" file.

### Do you plan to address this issue and file a PR?

I'm not able to do this.

**Comment by mateusz-holenko** [comment]
Hi @zxsoft, describing platforms in Renode is done with `repl` files. You use them to select which hardware components your platform should have and how those elements are connected together.

`platforms/cpus/cortex-a53-gicv3.repl` does not contain any ethernet controller, but extending it is just a matter of adding a few lines of text. You can take a look at [ZynqMP](https://github.com/renode/renode/blob/e1de9cf7a0ce63c9c68ba9808160b4c5a2bc482d/platforms/cpus/zynqmp.repl#L182-L183) for reference.

Please note that Linux needs to be aware of the hardware configuration, so you need to adapt the DTS file accordingly.
