### ISSUE TITLE
Gtk# is required to run the application in a windows environment

### ISSUE THREAD

**Issue by Apacz87** [renode/renode#7]
Running application on Windows 10 system, using version 1.3 from zip file, results in program crash if Gtk# is not instaled. In the documentation from which I read, I did not find any information about this requirement. Gtk# it is only listed as required when compiling.

**Comment by PiotrZierhoffer** [comment]
Thank you for the report. We are most likely missing a dll, will investigate it soon.

**Comment by PiotrZierhoffer** [comment]
We are migrating from GTK# to WPF on Windows - so while this report is valid, we will be fixing in another way, completely removing the dependency.

When it's done, I'll close the issue.

**Comment by PiotrZierhoffer** [comment]
With the tag v1.4 this is no longer relevant, so I close the issue.
