### ISSUE TITLE
Adding new CPUs and peripherals

### ISSUE THREAD

**Issue by jeremyherbert** [renode/renode#77]
Hi,

Is the code for the various peripherals available in the source tree? I can't seem to find it. I'm interested in possibly adding support for the STM32L4 series of microcontrollers.

Thanks.

**Comment by PiotrZierhoffer** [comment]
Hi Jeremy

Please look at the renode-infratructure repo. In fact it makes most sense to clone the Renode repo and download all the submodules - everything is there.
