### ISSUE TITLE
Windows - Renode crashes when closed with "x" button

### ISSUE THREAD

**Issue by AntonKrug** [renode/renode#8]
When renode is closed with the "x" button it creates crash popup window.

![renode-crash](https://user-images.githubusercontent.com/30338596/40542329-b3727ae4-6017-11e8-91be-912574f9c2f6.PNG)

This behaviour is not noticed when it's killed by some other mechanism, for example if the renode is launched with eclipse then if eclipse is killing it, it willl shutdown without any popup.

Note: The runtime behaviour or stability of the renode is not affected by this issue. So it's cosmetic problem.

**Comment by AntonKrug** [comment]
Great job with the 1.4 release.
Quickly tested with 64bit Windows 10 and it the crash seems to be resolved. Probably the issue can be closed and if it will resurface and proper testing I will update the issue.

**Comment by PiotrZierhoffer** [comment]
Yes, it was related to GTK releasing its resources. Now, with no GTK on Windows, it is resolved.
