### ISSUE TITLE
crash: Sequence contains no elements

### ISSUE THREAD

**Issue by xobs** [renode/renode#80]
The following commands crash renode:

```
mach create
machine StartGdbServer 3333 true
```

While this sequence is not valid, it should not crash Renode.

**Comment by PiotrZierhoffer** [comment]
Good catch, thanks. We'll push the fix to reach 1.9 release (should be ready today/tomorrow)

**Comment by PiotrZierhoffer** [comment]
This is fixed on master. Can you please verify if it works for you?

**Comment by xobs** [comment]
Yes, I've verified the fix works.
