### ISSUE TITLE
Support upgrading on Windows using MSI

### ISSUE THREAD

**Issue by xobs** [renode/renode#81]
Currently, it is impossible to upgrade Renode using the provided .msi.  If you attempt to install, the following dialog pops up:

![image](https://user-images.githubusercontent.com/238325/76488336-13337980-6460-11ea-9ec8-fe3d98ad22e3.png)

The workaround is to uninstall and reinstall, as it says.  It would be nice to support upgrading.

**Comment by PiotrZierhoffer** [comment]
This was actually fixed quite some time ago with d9686a7
