### ISSUE TITLE
Better packaging support

### ISSUE THREAD

**Issue by FFY00** [renode/renode#87]
Hello, I am interested in packaging renode but the support for proper packing seems to be very poor.

Here are some think I would need:
  - All required libraries should build be able to build shared objects and renode should support linking to them
  - The build system should not fetch anything by itself, I should be the one doing the fetching, verifying the sources (using checksums, GPG signatures, etc.) and put them in the right places (the main reason for this is reproducibility)
  - I should be able to pass my compiler and linking flags and the build system should not interfere with them

Would this be something you could be interested to do?

**Comment by mgielda** [comment]
Dear @FFY00, if the packaging system does not fit your requirements and you have some ideas how to improve it, you are welcome to provide a pull request which will show what you mean.
