### ISSUE TITLE
Creating binary dump of sysbus.uart1 to file

### ISSUE THREAD

**Issue by gustavosinbandera1** [renode/renode#89]
Hi guys it's possible to dump the data that is written to the uart1 as a file? I've been
looking but i've only found how to dump logs, but I need the binary data to do some tests on it.

**Comment by PiotrZierhoffer** [comment]
Hi

Right now you can approach it via a socket and your own scripting:

```
emulation CreateServerSocketTerminal 3333 "backend" 
connector Connect sysbus.uart1 backend
```

Please note that we are working on a file backend - it should be available in a week or two.

**Comment by gustavosinbandera1** [comment]
Thanks for you reply, in this moment was possible to me get the goal, doing a new peripheral and put  code to open ports and write files, its no the best code but works, now I am going  to do the test with the suggested solution. https://gist.github.com/gustavosinbandera1/75b60fc25ff7bb513eb42148be566134

**Comment by mateusz-holenko** [comment]
Hi @gustavosinbandera1,

I'm writing to let you know that `UartFileBackend` has been just merged to Renode master: https://github.com/renode/renode-infrastructure/blob/master/src/Emulator/Extensions/Utilities/UartFileBackend.cs. 

You can use it to dump UART content to a file - just execute the following command in monitor:
```
(machine-0) uart CreateFileBackend @/tmp/uart.dump
```
(add `true` at the end if you want to disable buffering and flush each character right away - this might decrease performance though).

Hope it'll be useful to you!

**Comment by gustavosinbandera1** [comment]
Thanks, I appreciate you take your time to help me
