### ISSUE TITLE
RI5CY: floating point operation causes invalid instruction exception

### ISSUE THREAD

**Issue by tjurtsch** [renode/renode#90]
When emulating RI5CY RISC-V platform with F ISA extension enabled in REPL, the first floating point operation causes invalid instruction exception. Executed binary is Litex Bios.

I attach a zip with REPL, RESC, binary, elf and a little patch.
A little patch needs to be applied to src/Infrastructure to allow passing F extended cpu variant to the RI5CY class constructor.

To reproduce the error, run Renode with attached litex.resc file as argument.
Then connect to the emulator with GDB and set a breakpoint at main.c:675
First FLW instruction causes the exception.

Running Renode, version 1.9.0.23990

**Comment by PiotrZierhoffer** [comment]
Moving this conversation to other channels
